// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Service.Models;

public partial class CoreSupplier
{
    public int SupplierCode { get; set; }

    public string SupplierId { get; set; }

    public string SupplierName { get; set; }

    public string SupplierTitle { get; set; }

    public string SuppCode { get; set; }

    public string SupplierCategoryId { get; set; }

    public string SupplierTypeId { get; set; }

    public string SupplierCompany { get; set; }

    public string SupplierAddress { get; set; }

    public string City { get; set; }

    public string State { get; set; }

    public string ZipCode { get; set; }

    public string CountryId { get; set; }

    public string Phone { get; set; }

    public string Email { get; set; }

    public decimal? OpeningBalance { get; set; }

    public string ContatPerson1 { get; set; }

    public string Designation1 { get; set; }

    public string Phone1 { get; set; }

    public string ContatPerson2 { get; set; }

    public string Designation2 { get; set; }

    public string Phone2 { get; set; }

    public string ContatPerson3 { get; set; }

    public string Designation3 { get; set; }

    public string Phone3 { get; set; }

    public string Luser { get; set; }

    public DateTime? Ldate { get; set; }

    public string Lip { get; set; }

    public string Lmac { get; set; }

    public DateTime? ModifyDate { get; set; }

    public string Fax { get; set; }

    public string Url { get; set; }

    public string Email1 { get; set; }

    public string Email2 { get; set; }

    public string Email3 { get; set; }
}