// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Service.Models;

public partial class DefInvStockLevelManagement
{
    public int Tc { get; set; }

    public string Slmid { get; set; }

    public string ItemId { get; set; }

    public string WarehouseId { get; set; }

    public decimal? InStock { get; set; }

    public decimal? StockValue { get; set; }

    public decimal? ReorderLevel { get; set; }

    public decimal? MaxStock { get; set; }

    public decimal? MinStock { get; set; }

    public string Description { get; set; }

    public DateTime? Ldate { get; set; }

    public string Luser { get; set; }

    public string Lip { get; set; }

    public string Lmac { get; set; }

    public DateTime? ModifyDate { get; set; }

    public string CompanyCode { get; set; }

    public string EmployeeId { get; set; }
}