// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace GCTL.Service.Models
{
    public partial class Get_ItemHierarchyDataResult
    {
        [Column("mainTC", TypeName = "decimal(18,0)")]
        public decimal mainTC { get; set; }
        public string mainMainItemID { get; set; }
        public string mainMainItemName { get; set; }
        public string mainDescription { get; set; }
        public DateTime? mainLDate { get; set; }
        public string mainLUser { get; set; }
        public string mainLIP { get; set; }
        public string mainLMAC { get; set; }
        public DateTime? mainModifyDate { get; set; }
        public string mainCompanyCode { get; set; }
        public string mainEmployeeId { get; set; }
        [Column("subTC", TypeName = "decimal(18,0)")]
        public decimal? subTC { get; set; }
        public string subSubItemID { get; set; }
        public string subSubItemName { get; set; }
        public string subMainItemID { get; set; }
        public string subDescription { get; set; }
        public DateTime? subLDate { get; set; }
        public string subLUser { get; set; }
        public string subLIP { get; set; }
        public string subLMAC { get; set; }
        public DateTime? subModifyDate { get; set; }
        public string subCompanyCode { get; set; }
        public string subEmployeeID { get; set; }
        [Column("sub2TC", TypeName = "decimal(18,0)")]
        public decimal? sub2TC { get; set; }
        public string sub2SubItem2ID { get; set; }
        public string sub2SubItem2Name { get; set; }
        public string sub2Description { get; set; }
        public string sub2MainItemID { get; set; }
        public string sub2SubItemID { get; set; }
        public string sub2LUser { get; set; }
        public DateTime? sub2LDate { get; set; }
        public string sub2LIP { get; set; }
        public string sub2LMAC { get; set; }
        public DateTime? sub2ModifyDate { get; set; }
        public string sub2CompanyCode { get; set; }
        public string sub2EmployeeID { get; set; }
        [Column("itemTC", TypeName = "decimal(18,0)")]
        public decimal? itemTC { get; set; }
        public string itemItemID { get; set; }
        public string itemBuyerId { get; set; }
        public string itemMasterPurchaseOrder { get; set; }
        public string itemStyleId { get; set; }
        public string itemMainItemID { get; set; }
        public string itemSubItemID { get; set; }
        public string itemSubItem2ID { get; set; }
        public string itemItemName { get; set; }
        public string itemPrintName { get; set; }
        public string itemTechnicalSpecification { get; set; }
        public string itemItemCode { get; set; }
        public string itemBarcode { get; set; }
        public string itemOriginId { get; set; }
        public string itemManufactureId { get; set; }
        public string itemPackageTypeId { get; set; }
        [Column("itemPackageQuantity", TypeName = "decimal(18,3)")]
        public decimal? itemPackageQuantity { get; set; }
        [Column("itemItemQuantity", TypeName = "decimal(18,3)")]
        public decimal? itemItemQuantity { get; set; }
        public string itemItemUnit { get; set; }
        [Column("itemItemPrice", TypeName = "decimal(18,2)")]
        public decimal? itemItemPrice { get; set; }
        public string itemCurrencyId { get; set; }
        [Column("itemTotalAmount", TypeName = "decimal(18,2)")]
        public decimal? itemTotalAmount { get; set; }
        public string itemCurrencyId2 { get; set; }
        [Column("itemDiscount", TypeName = "decimal(18,2)")]
        public decimal? itemDiscount { get; set; }
        public string itemWarrantyStatus { get; set; }
        [Column("itemWarrantyTime", TypeName = "decimal(18,3)")]
        public decimal? itemWarrantyTime { get; set; }
        public string itemWarrantyType { get; set; }
        public string itemBranchID { get; set; }
        public string itemLUser { get; set; }
        public DateTime? itemLDate { get; set; }
        public string itemLIP { get; set; }
        public string itemLMAC { get; set; }
        public DateTime? itemModifyDate { get; set; }
        public string itemCompanyCode { get; set; }
        public string itemEmployeeID { get; set; }
        public string itemSupplierId { get; set; }
        public string itemItemTypeID { get; set; }
        public int? stockTC { get; set; }
        public string stockSLMID { get; set; }
        public string stockItemID { get; set; }
        public string stockWarehouseID { get; set; }
        [Column("stockInStock", TypeName = "decimal(18,2)")]
        public decimal? stockInStock { get; set; }
        [Column("stockStockValue", TypeName = "decimal(18,2)")]
        public decimal? stockStockValue { get; set; }
        [Column("stockReorderLevel", TypeName = "decimal(18,2)")]
        public decimal? stockReorderLevel { get; set; }
        [Column("stockMaxStock", TypeName = "decimal(18,2)")]
        public decimal? stockMaxStock { get; set; }
        [Column("stockMinStock", TypeName = "decimal(18,2)")]
        public decimal? stockMinStock { get; set; }
        public string stockDescription { get; set; }
        public DateTime? stockLDate { get; set; }
        public string stockLUser { get; set; }
        public string stockLIP { get; set; }
        public string stockLMAC { get; set; }
        public DateTime? stockModifyDate { get; set; }
        public string stockCompanyCode { get; set; }
        public string stockEmployeeID { get; set; }
    }
}
