// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace GCTL.Service.Models
{
    public partial class GetCostingReportFiltersResult
    {
        public string Code { get; set; }
        public string Name { get; set; }
    }
}
