// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace GCTL.Service.Models
{
    public partial class GetCostingReportByCostingIdResult
    {
        public string CostingId { get; set; }
        public DateTime? EntryDate { get; set; }
        public DateTime? EntryDateTime { get; set; }
        public string IssuedBy { get; set; }
        public string CheckedBy { get; set; }
        public string CheckedName { get; set; }
        public string Remarks { get; set; }
        public DateTime? ShipmentDate { get; set; }
        public string BuyerId { get; set; }
        public string BuyerName { get; set; }
        public string StyleId { get; set; }
        public string StyleName { get; set; }
        public string ProductId { get; set; }
        public string ItemName { get; set; }
        public string ProductDescription { get; set; }
        public string PoNo { get; set; }
        public string FunJobNo { get; set; }
        public string RefNo { get; set; }
        [Column("SubTotalAmountShhkg", TypeName = "decimal(18,2)")]
        public decimal SubTotalAmountShhkg { get; set; }
        [Column("SubTotalAmountBdt", TypeName = "decimal(18,2)")]
        public decimal SubTotalAmountBdt { get; set; }
        [Column("SubTotalAmountThb", TypeName = "decimal(18,2)")]
        public decimal SubTotalAmountThb { get; set; }
        [Column("TotalAmountShhkg", TypeName = "decimal(18,2)")]
        public decimal TotalAmountShhkg { get; set; }
        [Column("TotalAmountBdt", TypeName = "decimal(18,2)")]
        public decimal TotalAmountBdt { get; set; }
        [Column("TotalAmountThb", TypeName = "decimal(18,2)")]
        public decimal TotalAmountThb { get; set; }
        [Column("TotalMaterialCostOverseas", TypeName = "decimal(18,2)")]
        public decimal TotalMaterialCostOverseas { get; set; }
        [Column("TotalMaterialCostBdt", TypeName = "decimal(18,2)")]
        public decimal TotalMaterialCostBdt { get; set; }
        [Column("CmandProfit", TypeName = "decimal(18,2)")]
        public decimal CmandProfit { get; set; }
        [Column("HandlingCharge", TypeName = "decimal(18,2)")]
        public decimal HandlingCharge { get; set; }
        [Column("Ffprice", TypeName = "decimal(18,2)")]
        public decimal Ffprice { get; set; }
        [Column("ProductionUpCharge", TypeName = "decimal(18,2)")]
        public decimal ProductionUpCharge { get; set; }
        [Column("TotalMaterialCostBkk", TypeName = "decimal(18,2)")]
        public decimal TotalMaterialCostBkk { get; set; }
        [Column("InterestOverheadPercentage", TypeName = "decimal(18,2)")]
        public decimal InterestOverheadPercentage { get; set; }
        [Column("DamagePercentage", TypeName = "decimal(18,2)")]
        public decimal DamagePercentage { get; set; }
        public string LUser { get; set; }
    }
}
