// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace GCTL.Service.Models
{
    public partial class GetOfficialInfoFilterResult
    {
        public string EmployeeID { get; set; }
        public string EmpName { get; set; }
        public string DesignationName { get; set; }
        public string DepartmentName { get; set; }
        public string BranchName { get; set; }
        public string EmploymentNature { get; set; }
        public string EmpTypeName { get; set; }
        public string JoiningDate { get; set; }
        public string SeparationDate { get; set; }
        public string ServiceLength { get; set; }
        public string ShiftName { get; set; }
        public string ImmediateSupervisorName { get; set; }
        public string HeadOfDepartmentName { get; set; }
        public string MobileNo { get; set; }
        public string Email { get; set; }
        public string EmployeeStatus { get; set; }
        public string NationalIdno { get; set; }
        public string TinNo { get; set; }
        public string PassportNo { get; set; }
        public string LicenseNo { get; set; }
        [Column("GrossSalary", TypeName = "decimal(18,2)")]
        public decimal GrossSalary { get; set; }
        public DateTime? AppointmentLetterDate { get; set; }
        public DateTime? ProbationEffectDate { get; set; }
        public DateTime? ConfirmeDate { get; set; }
    }
}
