// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Service.Models;

public partial class HrmAtdManual
{
    public decimal AutoId { get; set; }

    public string ManualCode { get; set; }

    public string BulkEntryId { get; set; }

    public string AttdEntryType { get; set; }

    public string EmployeeId { get; set; }

    public string AttendanceTypeCode { get; set; }

    public DateTime Date { get; set; }

    public DateTime Time { get; set; }

    public string Remarks { get; set; }

    public string Luser { get; set; }

    public DateTime? Ldate { get; set; }

    public string Lip { get; set; }

    public string Lmac { get; set; }

    public DateTime? ModifyDate { get; set; }

    public string CompanyCode { get; set; }

    public string Latitude { get; set; }

    public string Longitude { get; set; }

    public string EntryVia { get; set; }

    public string MonthName { get; set; }

    public string YearName { get; set; }

    public string DayName { get; set; }
}