// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Service.Models;

public partial class HrmAtdHoliday
{
    public decimal AutoId { get; set; }

    public string HolidayCode { get; set; }

    public string HolidayTypeCode { get; set; }

    public DateTime FromDate { get; set; }

    public DateTime ToDate { get; set; }

    public byte NoOfDays { get; set; }

    public string HolidayName { get; set; }

    public string HolidayType { get; set; }

    public string Luser { get; set; }

    public DateTime? Ldate { get; set; }

    public string Lip { get; set; }

    public string Lmac { get; set; }

    public DateTime? ModifyDate { get; set; }

    public virtual HrmDefHolidayType HolidayTypeCodeNavigation { get; set; }
}