// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Service.Models;

public partial class HrmAtdShift
{
    public decimal AutoId { get; set; }

    public string ShiftCode { get; set; }

    public string ShiftName { get; set; }

    public string ShiftShortName { get; set; }

    public DateTime ShiftStartTime { get; set; }

    public DateTime ShiftEndTime { get; set; }

    public DateTime LateTime { get; set; }

    public DateTime AbsentTime { get; set; }

    public DateTime Wef { get; set; }

    public string Remarks { get; set; }

    public string Luser { get; set; }

    public DateTime? Ldate { get; set; }

    public string Lip { get; set; }

    public string Lmac { get; set; }

    public DateTime? ModifyDate { get; set; }

    public string ShiftTypeId { get; set; }

    public DateTime LunchInTime { get; set; }

    public DateTime LunchOutTime { get; set; }

    public decimal LunchBreakHour { get; set; }
}