// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Service.Models;

public partial class HrmDefLine
{
    public decimal AutoId { get; set; }

    public string LineCode { get; set; }

    public string LineName { get; set; }

    public string LineCapacity { get; set; }

    public string Luser { get; set; }

    public DateTime? Ldate { get; set; }

    public string Lip { get; set; }

    public string Lmac { get; set; }

    public DateTime? ModifyDate { get; set; }

    public string CompanyCode { get; set; }

    public string SectionCode { get; set; }

    public string BanglaLine { get; set; }
}