// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Service.Models;

public partial class HrmDefHolidayType
{
    public decimal AutoId { get; set; }

    public string HolidayTypeCode { get; set; }

    public string ShortName { get; set; }

    public string HolidayType { get; set; }

    public string Luser { get; set; }

    public DateTime? Ldate { get; set; }

    public string Lip { get; set; }

    public string Lmac { get; set; }

    public DateTime? ModifyDate { get; set; }

    public string CompanyCode { get; set; }

    public virtual ICollection<HrmAtdHoliday> HrmAtdHolidays { get; set; } = new List<HrmAtdHoliday>();
}