// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Service.Models;

public partial class HrmDefUnitConversion
{
    public decimal AutoId { get; set; }

    public string UnitConversionId { get; set; }

    public string FromUnitTypId { get; set; }

    public string ToUnitTypId { get; set; }

    public decimal? UnitValue { get; set; }

    public decimal? UnitConversionValue { get; set; }

    public string Luser { get; set; }

    public DateTime? Ldate { get; set; }

    public string Lip { get; set; }

    public string Lmac { get; set; }

    public DateTime? ModifyDate { get; set; }

    public string CompanyCode { get; set; }

    public string UserInfoEmployeeId { get; set; }

    public string ThreadCountId { get; set; }
}