// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Service.Models;

public partial class HrmPayMonthlyTaxDepositEntry
{
    public decimal TaxDepositCode { get; set; }

    public string TaxDepositId { get; set; }

    public string EmployeeId { get; set; }

    public string FinancialCodeNo { get; set; }

    public decimal? TaxDepositAmount { get; set; }

    public string SalaryMonth { get; set; }

    public string SalaryYear { get; set; }

    public string TaxChallanNoPrefix { get; set; }

    public string TaxChallanNo { get; set; }

    public DateTime? TaxChallanDate { get; set; }

    public string BankId { get; set; }

    public string BankBranchId { get; set; }

    public string ApprovedStatus { get; set; }

    public string Remark { get; set; }

    public string Luser { get; set; }

    public DateTime? Ldate { get; set; }

    public string Lip { get; set; }

    public string Lmac { get; set; }

    public DateTime? ModifyDate { get; set; }

    public string CompanyCode { get; set; }

    public decimal? ChallanAmount { get; set; }
}