// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Service.Models;

public partial class InvDefCompanyFor
{
    public int Tc { get; set; }

    public string CompanyForId { get; set; }

    public string CompanyForName { get; set; }

    public DateTime? Ldate { get; set; }

    public string Luser { get; set; }

    public string Lip { get; set; }

    public string Lmac { get; set; }

    public DateTime? ModifyDate { get; set; }
}