// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Service.Models;

public partial class InvDefSalesPerson
{
    public int Tc { get; set; }

    public string SalesPersonId { get; set; }

    public string SalesPerson { get; set; }

    public string Address { get; set; }

    public string CompanyId { get; set; }

    public string DesignationId { get; set; }

    public string Phone { get; set; }

    public string Email { get; set; }

    public DateTime? Ldate { get; set; }

    public string Luser { get; set; }

    public string Lip { get; set; }

    public string Lmac { get; set; }

    public DateTime? ModifyDate { get; set; }

    public string CompanyCode { get; set; }

    public string EmployeeId { get; set; }

    public string Cpid { get; set; }
}