// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Service.Models;

public partial class InvDefWarehouseType
{
    public int WarehouseTypeCode { get; set; }

    public string WarehouseTypeId { get; set; }

    public string WarehouseTypeName { get; set; }

    public DateTime? Ldate { get; set; }

    public string Luser { get; set; }

    public string Lip { get; set; }

    public string Lmac { get; set; }

    public DateTime? ModifyDate { get; set; }

    public string WarehouseShortName { get; set; }
}