// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Service.Models;

public partial class InvDefPortInfo
{
    public int AutoId { get; set; }

    public string PortId { get; set; }

    public string PortName { get; set; }

    public string ShortName { get; set; }

    public string DeliveryMethodId { get; set; }

    public string PortAddress { get; set; }

    public string CountryId { get; set; }

    public string Luser { get; set; }

    public DateTime? Ldate { get; set; }

    public string Lip { get; set; }

    public string Lmac { get; set; }

    public DateTime? ModifyDate { get; set; }

    public string EmployeeId { get; set; }

    public string CompanyCode { get; set; }
}