// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Service.Models;

public partial class InvDefCompanyInfo
{
    public int Tc { get; set; }

    public string CompanyId { get; set; }

    public string CompanyName { get; set; }

    public string ShortName { get; set; }

    public string Address { get; set; }

    public string ZipCode { get; set; }

    public string City { get; set; }

    public string State { get; set; }

    public string CountryId { get; set; }

    public string Phone { get; set; }

    public string Fax { get; set; }

    public string Email { get; set; }

    public string Url { get; set; }

    public string Remarks { get; set; }

    public DateTime? Ldate { get; set; }

    public string Luser { get; set; }

    public string Lip { get; set; }

    public string Lmac { get; set; }

    public DateTime? ModifyDate { get; set; }

    public string CompanyCode { get; set; }

    public string EmployeeId { get; set; }

    public string LocalOfficeAddress { get; set; }

    public string CompanyForId { get; set; }
}