// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Service.Models;

public partial class InvDefWarehouse
{
    public int WarehouseCode { get; set; }

    public string WarehouseId { get; set; }

    public string WarehouseName { get; set; }

    public string WarehouseAddess { get; set; }

    public string WhTypeId { get; set; }

    public string City { get; set; }

    public string State { get; set; }

    public string ZipCode { get; set; }

    public string CountryId { get; set; }

    public string Area { get; set; }

    public string Remarks { get; set; }

    public string ContactPerson { get; set; }

    public string Designation { get; set; }

    public string ContactPersonPhone { get; set; }

    public string ContactPersonEmail { get; set; }

    public DateTime? Ldate { get; set; }

    public string Luser { get; set; }

    public string Lip { get; set; }

    public string Lmac { get; set; }

    public DateTime? ModifyDate { get; set; }
}