// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Service.Models;

public partial class InvDefDeliveryMethod
{
    public decimal Tc { get; set; }

    public string DeliveryMethodId { get; set; }

    public string DeliveryMethodName { get; set; }

    public DateTime? EntryDate { get; set; }

    public string LoginUserId { get; set; }

    public string LoginIpad { get; set; }

    public string LoginUserMacad { get; set; }

    public DateTime? ModifyDate { get; set; }

    public string CompanyId { get; set; }

    public string EmployeeId { get; set; }
}