// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Service.Models;

public partial class InvDefSupplierType
{
    public int SupplierTypeCode { get; set; }

    public string SupplierTypeId { get; set; }

    public string SupplierTypeName { get; set; }

    public DateTime? Ldate { get; set; }

    public string Luser { get; set; }

    public string Lip { get; set; }

    public string Lmac { get; set; }

    public DateTime? ModifyDate { get; set; }
}