// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Service.Models;

public partial class InvDefItem
{
    public decimal Tc { get; set; }

    public string ItemId { get; set; }

    public string BuyerId { get; set; }

    public string MasterPurchaseOrder { get; set; }

    public string StyleId { get; set; }

    public string MainItemId { get; set; }

    public string SubItemId { get; set; }

    public string SubItem2Id { get; set; }

    public string ItemName { get; set; }

    public string PrintName { get; set; }

    public string TechnicalSpecification { get; set; }

    public string ItemCode { get; set; }

    public string Barcode { get; set; }

    public string OriginId { get; set; }

    public string ManufactureId { get; set; }

    public string PackageTypeId { get; set; }

    public decimal? PackageQuantity { get; set; }

    public decimal? ItemQuantity { get; set; }

    public string ItemUnit { get; set; }

    public decimal? ItemPrice { get; set; }

    public string CurrencyId { get; set; }

    public decimal? TotalAmount { get; set; }

    public string CurrencyId2 { get; set; }

    public decimal? Discount { get; set; }

    public string WarrantyStatus { get; set; }

    public decimal? WarrantyTime { get; set; }

    public string WarrantyType { get; set; }

    public string BranchId { get; set; }

    public string Luser { get; set; }

    public DateTime? Ldate { get; set; }

    public string Lip { get; set; }

    public string Lmac { get; set; }

    public DateTime? ModifyDate { get; set; }

    public string CompanyCode { get; set; }

    public string EmployeeId { get; set; }

    public string SupplierId { get; set; }

    public string ItemTypeId { get; set; }
}