// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Service.Models;

public partial class InvItemPhoto
{
    public int AutoId { get; set; }

    public string ItemId { get; set; }

    public byte[] Photo { get; set; }

    public string ImgType { get; set; }

    public long ImgSize { get; set; }

    public string CompanyCode { get; set; }

    public string EmployeeId { get; set; }
}