// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Service.Models;

public partial class InvItemBrand
{
    public int Tc { get; set; }

    public string BrandId { get; set; }

    public byte[] BrandLogo { get; set; }

    public string ImgType { get; set; }

    public long ImgSize { get; set; }

    public string CompanyCode { get; set; }

    public string EmployeeId { get; set; }
}