// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace GCTL.Service.Models
{
    public partial class ProcGetEployeeFilterDetailsResult
    {
        public string FirstName { get; set; }
        public DateTime? JoiningDate { get; set; }
        public string DesignationName { get; set; }
        public string DepartmentName { get; set; }
        public string BranchName { get; set; }
        public string CompanyName { get; set; }
        public string EmpTypeName { get; set; }
        public string EmployeeStatus { get; set; }
    }
}
