// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Service.Models;

public partial class ProdDefBuyer
{
    public decimal Tc { get; set; }

    public string BuyerId { get; set; }

    public string Name { get; set; }

    public string ContactPersonName { get; set; }

    public string Address { get; set; }

    public string PostalCode { get; set; }

    public string Country { get; set; }

    public string Telephone { get; set; }

    public string Fax { get; set; }

    public string Email { get; set; }

    public string Website { get; set; }

    public string Active { get; set; }

    public string Note { get; set; }

    public string Luser { get; set; }

    public DateTime? Ldate { get; set; }

    public string Lip { get; set; }

    public string Lmac { get; set; }

    public DateTime? ModifyDate { get; set; }
}