// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Service.Models;

public partial class RmgBookingOrderDetail
{
    public decimal Id { get; set; }

    public string BookinOrderNo { get; set; }

    public string ItemOrderId { get; set; }

    public string Item { get; set; }

    public string ItemType { get; set; }

    public string ItemDiscription { get; set; }

    public string Color { get; set; }

    public byte[] SampleImage { get; set; }

    public decimal? ItemQuantity { get; set; }

    public string QuantityUnit { get; set; }

    public decimal? UnitPrice { get; set; }

    public string PriceCurrency { get; set; }

    public decimal? Discount { get; set; }

    public decimal? TotalAmount { get; set; }

    public string AmountCurrency { get; set; }

    public string Remarks { get; set; }

    public string Size { get; set; }

    public DateTime? EntryDate { get; set; }

    public string Lip { get; set; }

    public string Lmac { get; set; }

    public DateTime? ModifyDate { get; set; }

    public string EmployeeId { get; set; }

    public string CompanyId { get; set; }
}