// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Service.Models;

public partial class RmgBookingOrder
{
    public decimal Tc { get; set; }

    public string BookinOrderNo { get; set; }

    public DateTime BookinDate { get; set; }

    public string BuyerId { get; set; }

    public string StyleId { get; set; }

    public string MasterPurchaseOrder { get; set; }

    public string PoNo { get; set; }

    public string IntegraJobNo { get; set; }

    public string PurchasedOfficer { get; set; }

    public string Remarks { get; set; }

    public string Luser { get; set; }

    public DateTime? Ldate { get; set; }

    public string Lip { get; set; }

    public string Lmac { get; set; }

    public DateTime? ModifyDate { get; set; }

    public string EmployeId { get; set; }

    public string CompanyId { get; set; }

    public DateTime? DeliveryDate { get; set; }

    public string DeliveryAddress { get; set; }

    public string DeliveryMethod { get; set; }

    public string PaymentTerms { get; set; }

    public string TermsCondition { get; set; }

    public string BookingType { get; set; }

    public string BookingEntryType { get; set; }

    public string WarehouseId { get; set; }

    public string Pino { get; set; }

    public DateTime? Pidate { get; set; }

    public decimal? Pivalue { get; set; }

    public string PicurrencyId { get; set; }

    public string SupplierId { get; set; }

    public string Mrbpid { get; set; }

    public string EnterFromPageName { get; set; }

    public string PifilePath { get; set; }
}