// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Service.Models;

public partial class RmgCostingDetail
{
    public decimal Id { get; set; }

    public string CostingDetailsId { get; set; }

    public string CostingId { get; set; }

    public string Slno { get; set; }

    public string BookingItemTypeId { get; set; }

    public string ItemId { get; set; }

    public string Description { get; set; }

    public string Width { get; set; }

    public string ColorId { get; set; }

    public string SupplierId { get; set; }

    public string PoNo { get; set; }

    public decimal? Quantity { get; set; }

    public decimal? Consumption { get; set; }

    public decimal? Extra { get; set; }

    public decimal? TotalQuantity { get; set; }

    public string TotalQuantityUnit { get; set; }

    public decimal? UnitPrice { get; set; }

    public decimal? TotalPrice { get; set; }

    public string TotalPriceCurrencyId { get; set; }

    public decimal? TotalAmountShhkg { get; set; }

    public decimal? TotalAmountBdt { get; set; }

    public decimal? TotalAmountThb { get; set; }

    public string ResponsibleBy { get; set; }

    public string Luser { get; set; }

    public string BookinOrderNo { get; set; }
}