// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Service.Models;

public partial class RmgDefExportLcsalesContact
{
    public int Tc { get; set; }

    public string SalesContactId { get; set; }

    public string SalesContactNo { get; set; }

    public string ShortName { get; set; }

    public string Remarks { get; set; }

    public string Luser { get; set; }

    public DateTime? Ldate { get; set; }

    public string Lip { get; set; }

    public string Lmac { get; set; }

    public DateTime? ModifyDate { get; set; }

    public string CompanyCode { get; set; }

    public string UserInfoEmployeeId { get; set; }
}