// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Service.Models;

public partial class RmgInvBookingReceivedDetailsPolyTemp
{
    public int Id { get; set; }

    public string PurchaseReceiveNo { get; set; }

    public string Brdid { get; set; }

    public int? SerialNo { get; set; }

    public string ItemId { get; set; }

    public string ItemDescription { get; set; }

    public string ColorId { get; set; }

    public string RefernceCode { get; set; }

    public string Length { get; set; }

    public string LengthUnitId { get; set; }

    public string Width { get; set; }

    public string WidthUnitId { get; set; }

    public string Flap { get; set; }

    public string FlapUnitId { get; set; }

    public string Guest { get; set; }

    public string GuestUnitId { get; set; }

    public decimal? GarmentQty { get; set; }

    public string GarmentQtyUnitId { get; set; }

    public decimal? Consumption { get; set; }

    public string ConsumptionUnitId { get; set; }

    public decimal? TotalQty { get; set; }

    public string TotalQtyUnitId { get; set; }

    public string Percentage { get; set; }

    public decimal? TotalReceivedQty { get; set; }

    public decimal? CurrentReceiveQty { get; set; }

    public string ReceivedUnitType { get; set; }

    public decimal? UnitPrice { get; set; }

    public decimal? ReceivedUnitPrice { get; set; }

    public decimal? TotalPrice { get; set; }

    public string CurrencyId { get; set; }

    public string Remarks { get; set; }

    public string EmployeeId { get; set; }

    public decimal? TotalReceivedQtyPre { get; set; }

    public decimal? PendingReceiveQty { get; set; }

    public decimal? PendingReceiveQtyPre { get; set; }

    public string IntegraJobNo { get; set; }

    public string PoNo { get; set; }
}