// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Service.Models;

public partial class RmgInvBookingReceivedDetailsThread
{
    public int Id { get; set; }

    public string PurchaseReceiveNo { get; set; }

    public string Brdid { get; set; }

    public int? Slno { get; set; }

    public string ColorId { get; set; }

    public string ItemId { get; set; }

    public string FebricDetail { get; set; }

    public string ThreadColorId { get; set; }

    public decimal? OrderQty { get; set; }

    public string QtyUnitId { get; set; }

    public string ThreadCountId { get; set; }

    public string Refcodepantone { get; set; }

    public decimal? Consumption { get; set; }

    public string ConsumtionUnitId { get; set; }

    public decimal? TotalQty { get; set; }

    public string TotalQtyUnitId { get; set; }

    public decimal? ReqQty { get; set; }

    public string ThreadReqUnit { get; set; }

    public string Threadpercent { get; set; }

    public decimal? TotalReceivedQty { get; set; }

    public decimal? CurrentReceiveQty { get; set; }

    public string ReceivedUnitType { get; set; }

    public decimal? UnitPrice { get; set; }

    public decimal? ReceivedUnitPrice { get; set; }

    public decimal? TotalPrice { get; set; }

    public string CurrencyId { get; set; }

    public string Remarks { get; set; }

    public string EmployeeId { get; set; }

    public decimal? TotalReceivedQtyPre { get; set; }

    public decimal? PendingReceiveQty { get; set; }

    public decimal? PendingReceiveQtyPre { get; set; }

    public string IntegraJobNo { get; set; }

    public string PoNo { get; set; }
}