// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Service.Models;

public partial class RmgInvBookingReceivedDetailsCarton
{
    public int Id { get; set; }

    public string PurchaseReceiveNo { get; set; }

    public string Brdid { get; set; }

    public int? Slno { get; set; }

    public string ItemId { get; set; }

    public string ItemDescription { get; set; }

    public string ColorId { get; set; }

    public string SizeId { get; set; }

    public string Refcode { get; set; }

    public string CartonLeangth { get; set; }

    public string LeangthUnitId { get; set; }

    public string CartonWidth { get; set; }

    public string WidthUnitId { get; set; }

    public string CatonHeight { get; set; }

    public string HeightUnitId { get; set; }

    public decimal? OrderQty { get; set; }

    public string OrderUnitId { get; set; }

    public decimal? Consumption { get; set; }

    public string ConsumptionUnitId { get; set; }

    public decimal? RequiredQty { get; set; }

    public string RequiredQtyUnitId { get; set; }

    public decimal? CartonPercent { get; set; }

    public decimal? TotalReceivedQty { get; set; }

    public decimal? CurrentReceiveQty { get; set; }

    public string ReceivedUnitType { get; set; }

    public decimal? UnitPrice { get; set; }

    public decimal? ReceivedUnitPrice { get; set; }

    public decimal? TotalPrice { get; set; }

    public string CurrencyId { get; set; }

    public string Remarks { get; set; }

    public string EmployeeId { get; set; }

    public decimal? TotalReceivedQtyPre { get; set; }

    public decimal? PendingReceiveQty { get; set; }

    public decimal? PendingReceiveQtyPre { get; set; }

    public string IntegraJobNo { get; set; }

    public string PoNo { get; set; }
}