// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Service.Models;

public partial class RmgProdDefBuyerPhoto
{
    public decimal Tc { get; set; }

    public string BuyerId { get; set; }

    public byte[] Photo { get; set; }

    public string ImgType { get; set; }

    public long ImgSize { get; set; }
}