// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Service.Models;

public partial class RmgProdDefBuyer
{
    public decimal Tc { get; set; }

    public string BuyerId { get; set; }

    public string BuyerName { get; set; }

    public string Address { get; set; }

    public string LocalOfficeAddress { get; set; }

    public string CompanyId { get; set; }

    public string BuyerDepartmentId { get; set; }

    public string CountryId { get; set; }

    public string Phone { get; set; }

    public string Fax { get; set; }

    public string Email { get; set; }

    public string Url { get; set; }

    public string ContatPerson1 { get; set; }

    public string DesignationId { get; set; }

    public string Phone1 { get; set; }

    public string Email1 { get; set; }

    public string ContatPerson2 { get; set; }

    public string DesignationId2 { get; set; }

    public string Phone2 { get; set; }

    public string Email2 { get; set; }

    public string ContatPerson3 { get; set; }

    public string DesignationId3 { get; set; }

    public string Phone3 { get; set; }

    public string Email3 { get; set; }

    public string BuyerTypeId { get; set; }

    public string SalesPersonId { get; set; }

    public string Remarks { get; set; }

    public string Active { get; set; }

    public string Luser { get; set; }

    public DateTime? Ldate { get; set; }

    public string Lip { get; set; }

    public string Lmac { get; set; }

    public DateTime? ModifyDate { get; set; }

    public string CompanyCode { get; set; }
}