// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Service.Models;

public partial class RmgProdDefDeliveryAddress
{
    public decimal Tc { get; set; }

    public string DeliveryAddressId { get; set; }

    public string BuyerId { get; set; }

    public string Name { get; set; }

    public string DeliveryAddress { get; set; }

    public string ContactPerson { get; set; }

    public string Designation { get; set; }

    public string Phone { get; set; }

    public string Email { get; set; }

    public string Luser { get; set; }

    public DateTime? Ldate { get; set; }

    public string Lip { get; set; }

    public string Lmac { get; set; }

    public DateTime? ModifyDate { get; set; }
}