// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Service.Models;

public partial class RmgProdOrder
{
    public decimal Tc { get; set; }

    public string OrderId { get; set; }

    public DateTime Date { get; set; }

    public string BuyerId { get; set; }

    public string BuyerOrderNo { get; set; }

    public DateTime? BuyerOrderDate { get; set; }

    public string MasterPurchaseOrder { get; set; }

    public DateTime MpoDate { get; set; }

    public string SeasonId { get; set; }

    public string SeasonYear { get; set; }

    public string SupplierId { get; set; }

    public decimal TotalOrderQuantity { get; set; }

    public string UnitTypId { get; set; }

    public decimal? TotalPrice { get; set; }

    public string CurrencyId { get; set; }

    public string PaymentTerm { get; set; }

    public string BuyerBankId { get; set; }

    public string BuyerBranchId { get; set; }

    public string CompanyOwnBankId { get; set; }

    public string CompanyOwnBranchId { get; set; }

    public string BuContatPerson { get; set; }

    public string BuDesignation1 { get; set; }

    public string Buphone { get; set; }

    public string BuEmail { get; set; }

    public string MerContatPerson { get; set; }

    public string MerDesignation1 { get; set; }

    public string Merphone { get; set; }

    public string MerEmail { get; set; }

    public string BuyerDeclaration { get; set; }

    public string InspectionInfo { get; set; }

    public string Remarks { get; set; }

    public string Luser { get; set; }

    public DateTime? Ldate { get; set; }

    public string Lip { get; set; }

    public string Lmac { get; set; }

    public DateTime? ModifyDate { get; set; }

    public string CompanyCode { get; set; }

    public string EmployeeId { get; set; }

    public string IntegraJobno { get; set; }

    public string PostatusId { get; set; }

    public string BuyerBrand { get; set; }

    public string StyleId { get; set; }

    public DateTime? OrderDate { get; set; }

    public string BuyerSwiftCode { get; set; }

    public string CompanySwiftCode { get; set; }

    public string MerchandiserContactId { get; set; }

    public string StylePowise { get; set; }

    public decimal? Fobamount { get; set; }

    public string CurrencyIdFob { get; set; }
}