// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Service.Models;

public partial class RmgProdDefBrand
{
    public decimal Tc { get; set; }

    public string BrandId { get; set; }

    public string BuyerId { get; set; }

    public string Name { get; set; }

    public string LogoMonogram { get; set; }

    public string Detail { get; set; }

    public string Luser { get; set; }

    public DateTime? Ldate { get; set; }

    public string Lip { get; set; }

    public string Lmac { get; set; }

    public DateTime? ModifyDate { get; set; }
}