// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Service.Models;

public partial class RmgProdDefInvSubItem2
{
    public decimal Tc { get; set; }

    public string SubItem2Id { get; set; }

    public string SubItem2Name { get; set; }

    public string Description { get; set; }

    public string MainItemId { get; set; }

    public string SubItemId { get; set; }

    public string Luser { get; set; }

    public DateTime? Ldate { get; set; }

    public string Lip { get; set; }

    public string Lmac { get; set; }

    public DateTime? ModifyDate { get; set; }

    public string CompanyCode { get; set; }

    public string EmployeeId { get; set; }
}