// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Service.Models;

public partial class RmgProdOrderDetail
{
    public decimal Tc { get; set; }

    public string DetailOrderId { get; set; }

    public string OrderId { get; set; }

    public DateTime Date { get; set; }

    public string ProductId { get; set; }

    public string Description { get; set; }

    public string BrandId { get; set; }

    public string Style { get; set; }

    public string RefNo { get; set; }

    public string Hscode { get; set; }

    public string PurchaseOrder { get; set; }

    public DateTime Podate { get; set; }

    public int OrderQuantity { get; set; }

    public string PounitTypId { get; set; }

    public decimal? UnitPrice { get; set; }

    public string CurrencyId { get; set; }

    public decimal? TotalAmount { get; set; }

    public string MaterialInfo { get; set; }

    public string PrintingInstruction { get; set; }

    public string WashingInstruction { get; set; }

    public string LabelInstruction { get; set; }

    public string PackagingInstruction { get; set; }

    public string OtherInstruction { get; set; }

    public DateTime DeliveryDate { get; set; }

    public string DeliveryAddress { get; set; }

    public string DeliveryTerm { get; set; }

    public string DeliveryMethod { get; set; }

    public string PortOfLoading { get; set; }

    public string PortOfDischarge { get; set; }

    public string Luser { get; set; }

    public DateTime? Ldate { get; set; }

    public string Lip { get; set; }

    public string Lmac { get; set; }

    public DateTime? ModifyDate { get; set; }

    public string CompanyCode { get; set; }

    public string SupplierId { get; set; }

    public string PaymentTermsId { get; set; }

    public string GarmentsTesting { get; set; }

    public string GarmentsInstruction { get; set; }

    public string GarmentReminderDay { get; set; }

    public string GarmentReminderType { get; set; }

    public string GarmnetRemainderMail { get; set; }

    public string IsGarmentTestRecieved { get; set; }

    public string GarmentTestAttachment { get; set; }

    public string FebricTesting { get; set; }

    public string FebricInstruction { get; set; }

    public string FebricReminderDay { get; set; }

    public string FebricReminderType { get; set; }

    public string FebricRemainderMail { get; set; }

    public string IsFebricTestRecieved { get; set; }

    public string FebricTestAttachment { get; set; }

    public string TransportNo { get; set; }

    public string IntegraJobNo { get; set; }

    public string MasterPurchaseOrder { get; set; }

    public decimal? Percentage1 { get; set; }

    public string DeliveryMethod2 { get; set; }

    public decimal? Percentage2 { get; set; }

    public string DeliveryMethod3 { get; set; }

    public decimal? Percentage3 { get; set; }

    public DateTime? XfactoryDate { get; set; }
}