// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Service.Models;

public partial class SalesSupplierBankAccount
{
    public decimal AutoId { get; set; }

    public string Sbaid { get; set; }

    public string SupplierId { get; set; }

    public string BankId { get; set; }

    public string BankBranchId { get; set; }

    public string AccountName { get; set; }

    public string Luser { get; set; }
}