// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace GCTL.Service.Models
{
    public partial class sp_GetOrderReportResult
    {
        public string OrderId { get; set; }
        public string BuyerId { get; set; }
        public string BuyerOrderNo { get; set; }
        public string MasterPurchaseOrder { get; set; }
        public DateTime? PODate { get; set; }
        public string DetailOrderId { get; set; }
        public string ProductId { get; set; }
        public string PurchaseOrder { get; set; }
        public string Style { get; set; }
        public string RefNo { get; set; }
        [Column("Jan-2026")]
        public string Jan2026 { get; set; }
        [Column("TotalQuantity", TypeName = "decimal(38,2)")]
        public decimal? TotalQuantity { get; set; }
        public int? DetailsQuantity { get; set; }
        public string ColorId { get; set; }
        public string SizeId { get; set; }
        public int? ColorSizeBreakupQuantity { get; set; }
    }
}
