// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace GCTL.Service.Models
{
    public partial class sp_GetFilteredAttendanceResult
    {
        public string EmployeeId { get; set; }
        public string EmployeeName { get; set; }
        public DateTime Date { get; set; }
        public DateTime Time { get; set; }
        public string FingerPrintId { get; set; }
        public string MachineId { get; set; }
        [Column("Latitude ")]
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public string Remarks { get; set; }
    }
}
