// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace GCTL.Service.Models
{
    public partial class SP_GetEmployeesByEmployeeIDsResult
    {
        [Column("autoId", TypeName = "decimal(18,0)")]
        public decimal autoId { get; set; }
        public string EmployeeID { get; set; }
        public string CompanyCode { get; set; }
        public string BranchCode { get; set; }
        public string DivisionCode { get; set; }
        public string DepartmentCode { get; set; }
        public string DesignationCode { get; set; }
        public string EmpTypeCode { get; set; }
        public string GradeCode { get; set; }
        public string EmploymentNatureId { get; set; }
        [Column("GrossSalary", TypeName = "decimal(18,2)")]
        public decimal GrossSalary { get; set; }
        public string CurrencyCode { get; set; }
        public string PaymentPeriodID { get; set; }
        public string DisbursementMethodId { get; set; }
        public string ShiftCode { get; set; }
        public string EmployeeStatus { get; set; }
        public string ReportingTo { get; set; }
        public string HOD { get; set; }
        public string MobileNo { get; set; }
        public string Email { get; set; }
        public string AppointmentLetterNo { get; set; }
        public DateTime? AppointmentLetterDate { get; set; }
        public DateTime? JoiningDate { get; set; }
        [Column("JoiningSalary", TypeName = "decimal(18,2)")]
        public decimal JoiningSalary { get; set; }
        public string ProbationPeriodType { get; set; }
        public string ProbationPeriod { get; set; }
        public DateTime? ConfirmeDate { get; set; }
        public string LUser { get; set; }
        public DateTime? LDate { get; set; }
        public string LIP { get; set; }
        public string LMAC { get; set; }
        public DateTime? ModifyDate { get; set; }
        public string CompanyCode_Session { get; set; }
        public string UserInfoEmployeeID { get; set; }
        public string StepNoId { get; set; }
        public string TecnicalSkillTypeID { get; set; }
        public string SalaryScaleID { get; set; }
        public DateTime? ContractEndDate { get; set; }
        public string SectionCode { get; set; }
        public string LineCode { get; set; }
        public string AttendenceID { get; set; }
        public string IsExpatriate { get; set; }
        [Column("ExpatriateBasicSalary", TypeName = "decimal(18,2)")]
        public decimal? ExpatriateBasicSalary { get; set; }
        [Column("ExpatriateHouseRent", TypeName = "decimal(18,2)")]
        public decimal? ExpatriateHouseRent { get; set; }
        [Column("ExpatriateConveyance", TypeName = "decimal(18,2)")]
        public decimal? ExpatriateConveyance { get; set; }
        [Column("ExpatriateMedical", TypeName = "decimal(18,2)")]
        public decimal? ExpatriateMedical { get; set; }
        [Column("LFA", TypeName = "decimal(18,2)")]
        public decimal? LFA { get; set; }
        [Column("MobileAllowance", TypeName = "decimal(18,2)")]
        public decimal? MobileAllowance { get; set; }
        public string ConfirmationRefNo { get; set; }
        public DateTime? ProbationEffectDate { get; set; }
        [Column("ModeOfPaymentInBankPercentage", TypeName = "decimal(18,2)")]
        public decimal? ModeOfPaymentInBankPercentage { get; set; }
        public string IsLunchBilEligible { get; set; }
        public string IsOverTimeEligible { get; set; }
        public string IsExtraDutyEligible { get; set; }
        public string IsGovtHolidayEligible { get; set; }
        public string IsAttendanceBonusEligible { get; set; }
        public string PayID { get; set; }
    }
}
