// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Service.Models;

public partial class TblDeliveryMethod
{
    public decimal Id { get; set; }

    public string DeliveryMethodId { get; set; }

    public string DeliveryMethodName { get; set; }

    public DateTime? EntryDate { get; set; }

    public DateTime? ModifyDate { get; set; }

    public string PcName { get; set; }

    public string HostAddress { get; set; }

    public string UserId { get; set; }
}