// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Service.Models;

public partial class TransportMaterial
{
    public decimal Id { get; set; }

    public decimal TransportId { get; set; }

    public string TbreceiveNo { get; set; }

    public string VehicleNo { get; set; }

    public string MaterialDescription { get; set; }

    public int? Quantity { get; set; }

    public string UnitTypeId { get; set; }

    public decimal? Weight { get; set; }

    public string UnitTypeIdWeight { get; set; }

    public decimal? Cbm { get; set; }
}