// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Data.Models
{
    public partial class AccCompanyOpeningBalance
    {
        public decimal AutoId { get; set; }
        public string ComOpeningBalanceCode { get; set; }
        public string MainCompanyCode { get; set; }
        public string SubSusidiaryLedgerCodeNo { get; set; }
        public decimal? OpeningBalance { get; set; }
        public string TrType { get; set; }
        public DateTime? OpeningDate { get; set; }
        public string Luser { get; set; }
        public DateTime? Ldate { get; set; }
        public string Lip { get; set; }
        public string Lmac { get; set; }
        public DateTime? ModifyDate { get; set; }
        public string CompanyCode { get; set; }
        public string UserInfoEmployeeId { get; set; }
    }
}