// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Data.Models
{
    public partial class AccSubSubsidiaryLedger
    {
        public decimal AutoId { get; set; }
        public string SubsidiaryLedgerCodeNo { get; set; }
        public string SubSusidiaryLedgerCodeNo { get; set; }
        public string SubSubsidiaryLedgerName { get; set; }
        public string ShortName { get; set; }
        public decimal? OpeningBalance { get; set; }
        public string TrType { get; set; }
        public DateTime? OpeningDate { get; set; }
        public string IsActive { get; set; }
        public string Luser { get; set; }
        public DateTime? Ldate { get; set; }
        public string Lip { get; set; }
        public string Lmac { get; set; }
        public DateTime? ModifyDate { get; set; }
        public string CashFlowTypeId { get; set; }
        public string CostCenterCodeNo { get; set; }
    }
}