// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Data.Models
{
    public partial class AccVoucherEntry
    {
        public AccVoucherEntry()
        {
            AccVoucherEntryDetails = new HashSet<AccVoucherEntryDetails>();
        }

        public decimal VoucherEntryAutoId { get; set; }
        public string CostCenterCodeNo { get; set; }
        public string FinancialYear { get; set; }
        public string PeriodCodeNo { get; set; }
        public string VoucherTypeCode { get; set; }
        public DateTime VoucherDate { get; set; }
        public string VoucherNo { get; set; }
        public string Narration { get; set; }
        public string Luser { get; set; }
        public DateTime? Ldate { get; set; }
        public string Lip { get; set; }
        public string Lmac { get; set; }
        public DateTime? ModifyDate { get; set; }
        public string CompanyCode { get; set; }
        public string UserInfoEmployeeId { get; set; }
        public string MainCompanyCode { get; set; }
        public string IsApproved { get; set; }
        public string InvoiceNo { get; set; }
        public string InvoiceFor { get; set; }
        public string ApprovedBy { get; set; }
        public DateTime? ApprovedDateTime { get; set; }
        public string IsChecked { get; set; }
        public string CheckedBy { get; set; }
        public DateTime? CheckedDateTime { get; set; }

        public virtual ICollection<AccVoucherEntryDetails> AccVoucherEntryDetails { get; set; }
    }
}