// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Data.Models
{
    public partial class BillGeneration
    {
        public decimal AutoId { get; set; }
        public string BillNo { get; set; }
        public DateTime BillDate { get; set; }
        public string BookingNo { get; set; }
        public decimal? BookingAmount { get; set; }
        public decimal? AdditionalCharges { get; set; }
        public decimal? DiscountPercent { get; set; }
        public decimal? DiscountAmount { get; set; }
        public decimal? VatPercent { get; set; }
        public decimal? TaxPercent { get; set; }
        public decimal? NetAmount { get; set; }
        public decimal? PaymentTermsId { get; set; }
        public string TermsConditionId { get; set; }
        public string Remarks { get; set; }
        public string Luser { get; set; }
        public DateTime? Ldate { get; set; }
        public string Lip { get; set; }
        public string Lmac { get; set; }
        public string CompanyCode { get; set; }
        public string LoginEmployeeId { get; set; }
    }
}