// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Data.Models
{
    public partial class CaDefCurrency
    {
        public decimal Tc { get; set; }
        public string CurrencyId { get; set; }
        public string CurrencyName { get; set; }
        public string ShortName { get; set; }
        public string Symbol { get; set; }
        public int? DecimalPlaces { get; set; }
        public string NegativeFormat { get; set; }
        public string Luser { get; set; }
        public DateTime? Ldate { get; set; }
        public string Lip { get; set; }
        public string Lmac { get; set; }
        public DateTime? ModifyDate { get; set; }
    }
}