// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace GCTL.Data.Models
{
    public partial class CheckPaymentByMrNoResult
    {
        public int AutoId { get; set; }
        public string MRNo { get; set; }
        public DateTime MRDateTime { get; set; }
        public string Receiver { get; set; }
        public string ReceiverId { get; set; }
        public string PatientId { get; set; }
        public string PatientName { get; set; }
        public string TestCategory { get; set; }
        public string TestName { get; set; }
        [Column("TestAmount", TypeName = "decimal(18,2)")]
        public decimal? TestAmount { get; set; }
        [Column("DiscountedAmount", TypeName = "decimal(18,2)")]
        public decimal? DiscountedAmount { get; set; }
        [Column("CommissionPercent", TypeName = "decimal(18,2)")]
        public decimal? CommissionPercent { get; set; }
        [Column("CommissionAmount", TypeName = "decimal(18,2)")]
        public decimal? CommissionAmount { get; set; }
        [Column("Payable", TypeName = "decimal(18,2)")]
        public decimal? Payable { get; set; }
        [Column("Paid", TypeName = "decimal(18,2)")]
        public decimal? Paid { get; set; }
        [Column("Due", TypeName = "decimal(18,2)")]
        public decimal? Due { get; set; }
        public string Remarks { get; set; }
        public string PaymentStatus { get; set; }
        public string LUser { get; set; }
        public DateTime? LDate { get; set; }
        public string LIP { get; set; }
        public string LMAC { get; set; }
        public DateTime? ModifyDate { get; set; }
        public string CompanyCode { get; set; }
    }
}
