// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace GCTL.Data.Models
{
    public partial class CommissionDetailsByDoctorResult
    {
        public string CommissionSetupId { get; set; }
        public string DoctorId { get; set; }
        public string TestCategoryId { get; set; }
        public string TestChargeId { get; set; }
        [Column("CommissionPercent", TypeName = "decimal(18,2)")]
        public decimal? CommissionPercent { get; set; }
        [Column("CommissionAmount", TypeName = "decimal(18,2)")]
        public decimal? CommissionAmount { get; set; }
        public DateTime? EffectiveFrom { get; set; }
        public DateTime? EffectiveTo { get; set; }
        public bool? Continuing { get; set; }
    }
}
