// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Data.Models
{
    public partial class CoreMeasurementUnit
    {
        public int AutoId { get; set; }
        public string UnitId { get; set; }
        public string UnitType { get; set; }
        public string UnitName { get; set; }
        public string ShortName { get; set; }
        public string Luser { get; set; }
        public DateTime? Ldate { get; set; }
        public string Lip { get; set; }
        public string Lmac { get; set; }
        public DateTime? ModifyDate { get; set; }
    }
}