// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Data.Models
{
    public partial class CoreBankAccountInformation
    {
        public decimal AutoId { get; set; }
        public string AccInfoId { get; set; }
        public string AccountName { get; set; }
        public string AccountNo { get; set; }
        public string BankId { get; set; }
        public string BranchId { get; set; }
        public string Luser { get; set; }
        public DateTime? Ldate { get; set; }
        public string Lip { get; set; }
        public string Lmac { get; set; }
        public DateTime? ModifyDate { get; set; }
        public string UserInfoEmployeeId { get; set; }
        public string CompanyCode { get; set; }
    }
}