// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Data.Models
{
    public partial class CoreMenuTab
    {
        public int Id { get; set; }
        public string MenuId { get; set; }
        public string Title { get; set; }
        public string PageUrl { get; set; }
        public string ParentId { get; set; }
        public string OrderBy { get; set; }
    }
}