// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Data.Models
{
    public partial class CoreAccessCode3
    {
        public int AccessId { get; set; }
        public string AccessCodeId { get; set; }
        public string AccessCodeName { get; set; }
        public string TitleCheck { get; set; }
        public string Title { get; set; }
        public string PageUrl { get; set; }
        public string ChkAdd { get; set; }
        public string ChkEdit { get; set; }
        public string ChkDelete { get; set; }
        public string ChkPrint { get; set; }
        public string ParentId { get; set; }
        public string MenuId { get; set; }
        public string OrderBy { get; set; }
        public string MenuText { get; set; }
        public string ControllerName { get; set; }
        public string ViewName { get; set; }
        public string Icon { get; set; }
    }
}