// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Data.Models
{
    public partial class CoreUserInfo
    {
        public int Id { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string Type { get; set; }
        public string Status { get; set; }
        public string AccessCode { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string EmployeeId { get; set; }
        public DateTime? Dob { get; set; }
        public string OffPhone { get; set; }
        public string PerPhone { get; set; }
        public string OffEmail { get; set; }
        public string PerEmail { get; set; }
        public string Role { get; set; }
        public string SingleSession { get; set; }
        public DateTime? EntryDate { get; set; }
        public string Luser { get; set; }
        public DateTime? Ldate { get; set; }
        public string Lip { get; set; }
        public string Lmac { get; set; }
        public string WorkStation { get; set; }
        public string Regulation { get; set; }
        public DateTime? ModifyDate { get; set; }
        public string AccessPermissionCompanyCode { get; set; }
        public string AccessPermissionDivisionCode { get; set; }
        public string AccessPermissionJobTitle { get; set; }
        public string Token { get; set; }
        public string AccessPermissionBranchCode { get; set; }
        public string SecureCode { get; set; }
    }
}