// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Data.Models
{
    public partial class CoreMenuTab2
    {
        public int AutoId { get; set; }
        public string MenuId { get; set; }
        public string Title { get; set; }
        public string ParentId { get; set; }
        public int OrderBy { get; set; }
        public string ControllerName { get; set; }
        public string ViewName { get; set; }
        public string Icon { get; set; }
        public bool IsActive { get; set; }
        public string TableName { get; set; }
    }
}