// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace GCTL.Data.Models
{
    public partial class EmployeeBankAndNomineeInformationReportSPResult
    {
        public string EmployeeID { get; set; }
        public string EmployeeName { get; set; }
        public string CompanyName { get; set; }
        public string BranchName { get; set; }
        public string DesignationName { get; set; }
        public string DepartmentName { get; set; }
        public string BankAccountName { get; set; }
        public string BankAccountNo { get; set; }
        public string ATMCardNo { get; set; }
        public string NomineeName { get; set; }
        public string Relationship { get; set; }
        public string PresentAddress { get; set; }
        public string PermanentAddress { get; set; }
        public string BankName { get; set; }
        public string BankBranchName { get; set; }
        public string NationalIDNO { get; set; }
        public byte[] NomineePhoto { get; set; }
        public byte[] NomineeSignature { get; set; }
    }
}
