// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace GCTL.Data.Models
{
    public partial class EmployeeLoanInformationReportResult
    {
        public string LoanID { get; set; }
        public int? TotalLoans { get; set; }
        public string CompanyName { get; set; }
        public string CompanyCode { get; set; }
        public string EmployeeID { get; set; }
        public int? InstallmentNo { get; set; }
        public string InstallmentDate { get; set; }
        public string FullName { get; set; }
        public string DepartmentName { get; set; }
        public string DesignationName { get; set; }
        public string Reason { get; set; }
        [Column("LoanAmount", TypeName = "decimal(18,2)")]
        public decimal? LoanAmount { get; set; }
        public string LoanRepaymentMethod { get; set; }
        public DateTime? StartDate { get; set; }
        public DateTime? EndDate { get; set; }
        [Column("Installment Details")]
        public string InstallmentDetails { get; set; }
        public string PaymentMode { get; set; }
        [Column("Deposit", TypeName = "decimal(38,2)")]
        public decimal Deposit { get; set; }
        public string Remarks { get; set; }
        public DateTime? LoanDate { get; set; }
        public string LoanTypeID { get; set; }
        public string LoanType { get; set; }
        public string NoOfInstallment { get; set; }
        [Column("MonthlyDeduction", TypeName = "decimal(18,2)")]
        public decimal? MonthlyDeduction { get; set; }
        [Column("Outstanding Balance", TypeName = "decimal(38,2)")]
        public decimal? OutstandingBalance { get; set; }
    }
}
