// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace GCTL.Data.Models
{
    public partial class EmployeeGeneralInfoReportSPResult
    {
        public string EmployeeID { get; set; }
        public string EmployeeName { get; set; }
        public string FatherName { get; set; }
        public string MotherName { get; set; }
        public string Nationality { get; set; }
        public string CompanyName { get; set; }
        public string NationalIDNO { get; set; }
        public string DateOfBirthCertificate { get; set; }
        public string PlaceOfBirth { get; set; }
        public string Sex { get; set; }
        public string BloodGroup { get; set; }
        public string Religion { get; set; }
        public string PresentAddress { get; set; }
        public string ParmanentAddress { get; set; }
        public string Telephone { get; set; }
        public string PersonalEmail { get; set; }
        public string TinNo { get; set; }
        public string MaritalStatus { get; set; }
        public string DepartmentName { get; set; }
        public string DesignationName { get; set; }
    }
}
