// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace GCTL.Data.Models
{
    public partial class EmployeeReferenceInformationReportSPResult
    {
        public string EmployeeID { get; set; }
        public string EmployeeName { get; set; }
        public string DepartmentName { get; set; }
        public string DesignationName { get; set; }
        public string JoiningDate { get; set; }
        public string NationalIDNO { get; set; }
        public string ReferenceName { get; set; }
        public string OrganizationName { get; set; }
        public string DesignationNameRef { get; set; }
        public string RefAddress { get; set; }
        public string Nationality { get; set; }
        public string Relationship { get; set; }
        public string PhoneNumber { get; set; }
        public string MobileNumber { get; set; }
        public string Email { get; set; }
    }
}
