// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace GCTL.Data.Models
{
    public partial class FullEmployeeDetailsGetByidResult
    {
        public string CompanyCode { get; set; }
        public string CompanyName { get; set; }
        public string Address1 { get; set; }
        public string CompanyCountry { get; set; }
        public string CompanyAddress { get; set; }
        public string EmployeeID { get; set; }
        public string EmployeeName { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string FatherName { get; set; }
        public string MotherName { get; set; }
        public string FathersOccupation { get; set; }
        public string MothersOccupation { get; set; }
        public string DateOfBirthCertificate { get; set; }
        public string DateOfBirthOrginal { get; set; }
        public string PlaceOfBirth { get; set; }
        public string NationalIDNO { get; set; }
        public string BirthCertificateNo { get; set; }
        public string NoOfSon { get; set; }
        public string NoOfDaughters { get; set; }
        public string Telephone { get; set; }
        public string TINNo { get; set; }
        public string ExtraCurricularActivities { get; set; }
        public string PersonalEmail { get; set; }
        public string CardNo { get; set; }
        public string GenderCode { get; set; }
        public string Gender { get; set; }
        public string MaritalStatusCode { get; set; }
        public string MaritalStatus { get; set; }
        public string BloodGroupCode { get; set; }
        public string BloodGroup { get; set; }
        public string NationalityCode { get; set; }
        public string Nationality { get; set; }
        public string ReligionCode { get; set; }
        public string Religion { get; set; }
        public string PassportNo { get; set; }
        public string PassportExpiryDate { get; set; }
        public string DrivingLicenseNo { get; set; }
        public string DrivingLicenseExpiryDate { get; set; }
        public string WorkPermitNo { get; set; }
        public string WorkPermitType { get; set; }
        public DateTime WpEffectiveDate { get; set; }
        public DateTime WpExpireDate { get; set; }
        public string BranchCode { get; set; }
        public string BranchName { get; set; }
        public string DivisionCode { get; set; }
        public string DivisionName { get; set; }
        public string DepartmentCode { get; set; }
        public string DepartmentName { get; set; }
        public string DesignationCode { get; set; }
        public string DesignationName { get; set; }
        public string EmployeeTypeCode { get; set; }
        public string EmployeeType { get; set; }
        public string EmploymentNatureId { get; set; }
        public string EmploymentNature { get; set; }
        public string GradeCode { get; set; }
        public string GradeNo { get; set; }
        [Column("GrossSalary", TypeName = "decimal(18,2)")]
        public decimal GrossSalary { get; set; }
        [Column("JoiningSalary", TypeName = "decimal(18,2)")]
        public decimal JoiningSalary { get; set; }
        public string ShiftCode { get; set; }
        public string ShiftName { get; set; }
        public string ClientIdRaw { get; set; }
        public string ModeOfPayment { get; set; }
        [Column("ModeOfPaymentInBankPercentage", TypeName = "decimal(18,2)")]
        public decimal ModeOfPaymentInBankPercentage { get; set; }
        public string EmployeeStatusId { get; set; }
        public string EmployeeStatus { get; set; }
        public string ImmediateSupervisorID { get; set; }
        public string ImmediateSupervisor { get; set; }
        public string HeadOfDepartmentID { get; set; }
        public string HeadOfDepartment { get; set; }
        public string OfficialPhone { get; set; }
        public string OfficialEmail { get; set; }
        public string PayId { get; set; }
        public string AttendenceId { get; set; }
        public string AppointmentLetterNo { get; set; }
        public string AppointmentLetterDate { get; set; }
        public string JoiningDate { get; set; }
        public string ProbationPeriodType { get; set; }
        public string ProbationPeriod { get; set; }
        public string ProbationEndDate { get; set; }
        public string ConfirmationDate { get; set; }
        public string ConfirmationRefNo { get; set; }
        public string ContractEndDate { get; set; }
        public string IsLunchBilEligible { get; set; }
        public string IsOverTimeEligible { get; set; }
        public string IsExtraDutyEligible { get; set; }
        public string IsGovtHolidayEligible { get; set; }
        public string IsAttendanceBonusEligible { get; set; }
        public string ServiceLength { get; set; }
        public string LeavingDate { get; set; }
        public string PresentAddress { get; set; }
        public string PresentPostOffice { get; set; }
        public string PresentThana { get; set; }
        public string PresentPostCode { get; set; }
        public string PresentDistrict { get; set; }
        public string PresentMobile { get; set; }
        public string PresentPhone { get; set; }
        public string PresentFax { get; set; }
        public string PresentEmail { get; set; }
        public string PresentAddressBangla { get; set; }
        public string ParmanentAddress { get; set; }
        public string ParmanentPostOffice { get; set; }
        public string ParmanentThana { get; set; }
        public string ParmanentPostCode { get; set; }
        public string ParmanentDistrict { get; set; }
        public string ParmanentPhone { get; set; }
        public string ParmanentAddressBangla { get; set; }
        public string EmContactName1 { get; set; }
        public string EmContactRelation1Code { get; set; }
        public string EmContactRelation1 { get; set; }
        public string EmContactMobile1 { get; set; }
        public string EmContactPhone1 { get; set; }
        public string EmContactEmail { get; set; }
        public string EmContactName2 { get; set; }
        public string EmContactRelation2Code { get; set; }
        public string EmContactRelation2 { get; set; }
        public string EmContactMobile2 { get; set; }
        public string EmContactPhone2 { get; set; }
        public string EmContactEmai2 { get; set; }
        public string HighestExamTitle { get; set; }
        public string HighestInstitute { get; set; }
        public string HighestBoard { get; set; }
        public string HighestGroup { get; set; }
        public string HighestResult { get; set; }
        public string HighestCgpa { get; set; }
        public string HighestScaleOf { get; set; }
        public string HighestYearOfPassing { get; set; }
        public string HighestDuration { get; set; }
        public string HighestDurationType { get; set; }
        public string HighestAchievement { get; set; }
        public byte[] Photo { get; set; }
        public byte[] DigitalSignature { get; set; }
    }
}
