// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace GCTL.Data.Models
{
    public partial class GetAdvancePayPagedWithFilterResult
    {
        public string AdvancePayId { get; set; }
        public string EmployeeID { get; set; }
        public string FullName { get; set; }
        public string DepartmentName { get; set; }
        public string DesignationName { get; set; }
        [Column("AdvanceAmount", TypeName = "decimal(10,2)")]
        public decimal AdvanceAmount { get; set; }
        [Column("MonthlyDeduction", TypeName = "decimal(10,2)")]
        public decimal MonthlyDeduction { get; set; }
        public string SalaryMonth { get; set; }
        public string SalaryYear { get; set; }
        public string NoOfPaymentInstallment { get; set; }
        public string PayHeadNameId { get; set; }
        public string Remarks { get; set; }
        public string LoanID { get; set; }
        public string AdjustmentType { get; set; }
        public string AdvanceAdjustStatus { get; set; }
        public DateTime? JoiningDate { get; set; }
        public DateTime? LoanDate { get; set; }
        public string LoanTypeID { get; set; }
        public DateTime? StartDate { get; set; }
        public DateTime? EndDate { get; set; }
        [Column("AdvancePayCode", TypeName = "decimal(18,0)")]
        public decimal AdvancePayCode { get; set; }
        public DateTime? LDate { get; set; }
        public DateTime? ModifyDate { get; set; }
    }
}
