// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace GCTL.Data.Models
{
    public partial class GetCompanyNamesBySearchResult
    {
        public string CompanyCode { get; set; }
        public string CompanyName { get; set; }
    }
}
