// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace GCTL.Data.Models
{
    public partial class GetDiscountDetailsResult
    {
        public string DiscountSetupId { get; set; }
        public string TestCategoryId { get; set; }
        public string TestChargeId { get; set; }
        [Column("DiscountPercent", TypeName = "decimal(18,2)")]
        public decimal? DiscountPercent { get; set; }
        [Column("DiscountAmount", TypeName = "decimal(18,2)")]
        public decimal? DiscountAmount { get; set; }
        public DateTime? EffectiveFrom { get; set; }
        public DateTime? EffectiveTo { get; set; }
        public bool? Continuing { get; set; }
    }
}
