// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace GCTL.Data.Models
{
    public partial class GetEmployeeQualificationDetails1Result
    {
        public string CourseCode { get; set; }
        public string CourseName { get; set; }
        public string InstituteName { get; set; }
        public string InstituteAddress { get; set; }
        public string Duration { get; set; }
        public string ResultDivision { get; set; }
        public string YearOfPassing { get; set; }
    }
}
