// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace GCTL.Data.Models
{
    public partial class GetEmployeeBankDetailsResult
    {
        public string BankName { get; set; }
        public string BankBranchName { get; set; }
        public string BankAccountName { get; set; }
        public string BankAccountNo { get; set; }
    }
}
