// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace GCTL.Data.Models
{
    public partial class GetEmployeesByCompanyAdvanceLoanAdjustmentResult
    {
        public string EmployeeID { get; set; }
        public string FullName { get; set; }
        public string DepartmentName { get; set; }
        public string DesignationName { get; set; }
        public DateTime? JoiningDate { get; set; }
    }
}
