// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace GCTL.Data.Models
{
    public partial class GetEmployeeEducationDetailsResult
    {
        [Column("autoId", TypeName = "decimal(18,0)")]
        public decimal autoId { get; set; }
        public string EmployeeID { get; set; }
        public string ExamTitleName { get; set; }
        public string GroupName { get; set; }
        public string InstituteName { get; set; }
        public string BoardName { get; set; }
        public string ResultDivision { get; set; }
        public string YearofPasssing { get; set; }
        public string Dueration { get; set; }
    }
}
