// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace GCTL.Data.Models
{
    public partial class GetEmployeeReferenceDetailsResult
    {
        public string ReferenceName { get; set; }
        public string OrganizationName { get; set; }
        public string RefAddress { get; set; }
        public string Nationality { get; set; }
        public string DesignationName { get; set; }
        public string RelationShip { get; set; }
        public string MobileNumber { get; set; }
        public string Email { get; set; }
    }
}
