// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace GCTL.Data.Models
{
    public partial class GetLeaveEntriesResult
    {
        [Column("LeaveAppEntryCode", TypeName = "decimal(18,0)")]
        public decimal LeaveAppEntryCode { get; set; }
        public string LeaveAppEntryId { get; set; }
        public string EmployeeID { get; set; }
        public string EmployeeFirstName { get; set; }
        public string DepartmentName { get; set; }
        public string DesignationName { get; set; }
        public DateTime StartDate { get; set; }
        public DateTime EndDate { get; set; }
        [Column("NoOfDay", TypeName = "decimal(10,1)")]
        public decimal NoOfDay { get; set; }
        public DateTime? ModifyDate { get; set; }
        public string ConfirmationRemarks { get; set; }
        public string HODApprovalStatus { get; set; }
        public string HRApprovalRemarks { get; set; }
        public string SickLeaveFilePath { get; set; }
        public string HRApprovalStatus { get; set; }
        public string ApplyLeaveFormat { get; set; }
        public string HODFirstName { get; set; }
        public string SupervisorFirstName { get; set; }
        public string Reason { get; set; }
        public DateTime? ShortLeaveFrom { get; set; }
        public DateTime? ShortLeaveTo { get; set; }
        public TimeOnly? ShortLeaveTime { get; set; }
        public string IsApproved { get; set; }
        public string FirstOrSecondHalf { get; set; }
        public string Days { get; set; }
    }
}
