// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace GCTL.Data.Models
{
    public partial class GetOfficialInfoResult
    {
        public string EmployeeID { get; set; }
        public string EmpName { get; set; }
        public string DesignationName { get; set; }
        public string DepartmentName { get; set; }
        public string BranchName { get; set; }
        public string EmploymentNature { get; set; }
        public string EmpTypeName { get; set; }
        public string JoiningDate { get; set; }
        public string SeparationDate { get; set; }
        public string ServiceLength { get; set; }
        public string ShiftName { get; set; }
        public string ImmediateSupervisorName { get; set; }
        public string HeadOfDepartmentName { get; set; }
        public string MobileNo { get; set; }
        public string Email { get; set; }
        public string EmployeeStatus { get; set; }
    }
}
