// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace GCTL.Data.Models
{
    public partial class Gettermination2Result
    {
        public string EmployeeID { get; set; }
        public string EmpName { get; set; }
        public string DesignationName { get; set; }
        public string DepartmentName { get; set; }
        public string BranchName { get; set; }
        public string EmpTypeName { get; set; }
        public string SeparationDate { get; set; }
        public string SeparationType { get; set; }
        public string CompanyName { get; set; }
    }
}
