// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace GCTL.Data.Models
{
    public partial class GetTestRoomNoResult
    {
        public int AutoId { get; set; }
        public string SpecimenId { get; set; }
        public string Specimen { get; set; }
        public string TestCategoryCode { get; set; }
        public string TestChargeCode { get; set; }
        public string LUser { get; set; }
        public DateTime? LDate { get; set; }
        public string LIP { get; set; }
        public string LMAC { get; set; }
        public DateTime? ModifyDate { get; set; }
        public string CompanyCode { get; set; }
        public string RoomNo { get; set; }
        public string TestSubCategoryCode { get; set; }
        public string TestId { get; set; }
    }
}
