// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Data.Models
{
    public partial class HmsBillEntryDetails
    {
        public int AutoId { get; set; }
        public string BillEntryNo { get; set; }
        public string ServiceChargeGroupId { get; set; }
        public string ServiceChargeHeadId { get; set; }
        public int? NoOfDaysOrQuantity { get; set; }
        public decimal? Rate { get; set; }
        public decimal? Amount { get; set; }
        public decimal? DiscountPercent { get; set; }
        public decimal? DiscountAmount { get; set; }
        public decimal? AfterDiscountAmount { get; set; }
        public string Luser { get; set; }
    }
}