// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Data.Models
{
    public partial class HmsCommissionPaymentEntry
    {
        public int AutoId { get; set; }
        public string PaymentNo { get; set; }
        public DateTime PaymentDateTime { get; set; }
        public string PaymentHistoryId { get; set; }
        public string Receiver { get; set; }
        public string ReceiverId { get; set; }
        public string ReceiverName { get; set; }
        public string PaymentTypeId { get; set; }
        public string PaymentModeId { get; set; }
        public decimal? PaidAmount { get; set; }
        public string ChequeNo { get; set; }
        public DateTime? ChequeDate { get; set; }
        public string BankId { get; set; }
        public string TransferBankAccount { get; set; }
        public string TransferredBankFrom { get; set; }
        public string TransferredBankTo { get; set; }
        public string Remarks { get; set; }
        public string PaidBy { get; set; }
        public string Luser { get; set; }
        public DateTime? Ldate { get; set; }
        public string Lip { get; set; }
        public string Lmac { get; set; }
        public DateTime? ModifyDate { get; set; }
        public string CompanyCode { get; set; }
        public string PartialPaidId { get; set; }
        public decimal? PartialPaidAmount { get; set; }
        public string BkashNo { get; set; }
    }
}