// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Data.Models
{
    public partial class HmsCommissionPaymentHistory
    {
        public int AutoId { get; set; }
        public string Mrno { get; set; }
        public DateTime MrdateTime { get; set; }
        public string Receiver { get; set; }
        public string ReceiverId { get; set; }
        public string PatientId { get; set; }
        public string PatientName { get; set; }
        public string TestCategory { get; set; }
        public string TestName { get; set; }
        public decimal? TestAmount { get; set; }
        public decimal? DiscountedAmount { get; set; }
        public decimal? CommissionPercent { get; set; }
        public decimal? CommissionAmount { get; set; }
        public decimal? Payable { get; set; }
        public decimal? Paid { get; set; }
        public decimal? Due { get; set; }
        public string Remarks { get; set; }
        public string PaymentStatus { get; set; }
        public string Luser { get; set; }
        public DateTime? Ldate { get; set; }
        public string Lip { get; set; }
        public string Lmac { get; set; }
        public DateTime? ModifyDate { get; set; }
        public string CompanyCode { get; set; }
    }
}