// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Data.Models
{
    public partial class HmsCommissionSetup
    {
        public int AutoId { get; set; }
        public string CommissionSetupId { get; set; }
        public DateTime CommissionSetupDateTime { get; set; }
        public string CommissionReceiver { get; set; }
        public string DepartmentId { get; set; }
        public string DoctorId { get; set; }
        public string ReferenceId { get; set; }
        public string Remarks { get; set; }
        public string Luser { get; set; }
        public DateTime? Ldate { get; set; }
        public string Lip { get; set; }
        public string Lmac { get; set; }
        public DateTime? ModifyDate { get; set; }
        public string CompanyCode { get; set; }
    }
}