// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Data.Models
{
    public partial class HmsDoctorWorkingPlace
    {
        public decimal AutoId { get; set; }
        public string WorkingPlaceCode { get; set; }
        public string WorkingPlaceName { get; set; }
        public string WorkingPlaceShortName { get; set; }
        public string Luser { get; set; }
        public DateTime? Ldate { get; set; }
        public string Lip { get; set; }
        public string Lmac { get; set; }
        public DateTime? ModifyDate { get; set; }
        public string BanglaWorkingPlace { get; set; }
        public string BanglaShortName { get; set; }
        public string EmployeeId { get; set; }
        public string CompanyCode { get; set; }
    }
}