// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Data.Models
{
    public partial class HmsDoctorAppointmentDays
    {
        public string AppointmentCode { get; set; }
        public int AppointmentId { get; set; }
        public string AppointmentDays { get; set; }
        public string DoctorCode { get; set; }
        public TimeOnly? VisitingTimeFrom { get; set; }
        public TimeOnly? VisitingTimeTo { get; set; }
        public string Luser { get; set; }
        public DateTime? Ldate { get; set; }
        public string Lip { get; set; }
        public string Lmac { get; set; }
        public DateTime? ModifyDate { get; set; }
    }
}