// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Data.Models
{
    public partial class HmsDischargeMedicine
    {
        public int DischargeMedicineId { get; set; }
        public string DischargeId { get; set; }
        public string MedicineCode { get; set; }
        public string DosageCode { get; set; }
        public string TakeTime { get; set; }
        public string TakeUnit { get; set; }
        public string TakeCode { get; set; }
        public string Duration { get; set; }
        public string DurationCode { get; set; }
        public string Instruction { get; set; }
        public string Luser { get; set; }
        public DateTime? Ldate { get; set; }
        public string Lip { get; set; }
        public string Lmac { get; set; }
        public DateTime? ModifyDate { get; set; }
    }
}