// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Data.Models
{
    public partial class HmsExpenseEntry
    {
        public int AutoId { get; set; }
        public string ExpenseCode { get; set; }
        public DateTime ExpenseDate { get; set; }
        public string SubSusidiaryLedgerCodeNo { get; set; }
        public decimal Amount { get; set; }
        public string PaymentMode { get; set; }
        public string BkashNo { get; set; }
        public string ChequeNo { get; set; }
        public DateTime? ChequeDate { get; set; }
        public string BankAccountNo { get; set; }
        public string TransferBankFrom { get; set; }
        public string TransferBankTo { get; set; }
        public string Remarks { get; set; }
        public string Luser { get; set; }
        public DateTime? Ldate { get; set; }
        public string Lip { get; set; }
        public string Lmac { get; set; }
        public DateTime? ModifyDate { get; set; }
        public string CompanyCode { get; set; }
        public string EmployeeId { get; set; }
    }
}