// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Data.Models
{
    public partial class HmsLabTestReferenceSetup
    {
        public int AutoId { get; set; }
        public string LabTestReferenceId { get; set; }
        public string TestCategoryId { get; set; }
        public string TestChargeId { get; set; }
        public string Remarks { get; set; }
        public string Luser { get; set; }
        public DateTime? Ldate { get; set; }
        public string Lip { get; set; }
        public string Lmac { get; set; }
        public DateTime? ModifyDate { get; set; }
        public string CompanyCode { get; set; }
        public string TestSubCategoryId { get; set; }
    }
}