// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Data.Models
{
    public partial class HmsLabTestReferenceSetupDetails
    {
        public int AutoId { get; set; }
        public string LabTestReferenceId { get; set; }
        public string PersonId { get; set; }
        public string AgeFrom { get; set; }
        public string AgeTo { get; set; }
        public string PeriodId { get; set; }
        public string RangeFrom { get; set; }
        public string RangeTo { get; set; }
        public string UnitId { get; set; }
        public string Luser { get; set; }
        public string NormalValueText { get; set; }
    }
}