// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Data.Models
{
    public partial class HmsLabTestResult
    {
        public int AutoId { get; set; }
        public string LabTestNo { get; set; }
        public string ReportNo { get; set; }
        public DateTime ReportDateTime { get; set; }
        public DateTime? DeliveryDate { get; set; }
        public string PatientCode { get; set; }
        public string RegistrationId { get; set; }
        public string SpecimenId { get; set; }
        public string CarriedOutById { get; set; }
        public string Remarks { get; set; }
        public string PreparedBy { get; set; }
        public string Luser { get; set; }
        public DateTime? Ldate { get; set; }
        public string Lip { get; set; }
        public string Lmac { get; set; }
        public DateTime? ModifyDate { get; set; }
        public string CompanyCode { get; set; }
    }
}