// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Data.Models
{
    public partial class HmsLabTestResultDetails
    {
        public int AutoId { get; set; }
        public string ReportNo { get; set; }
        public string LabTestId { get; set; }
        public string TestCategoryCode { get; set; }
        public string TestChargeCode { get; set; }
        public DateTime? DeliveryDate { get; set; }
        public string Result { get; set; }
        public string Unitid { get; set; }
        public string Remarks { get; set; }
        public string Luser { get; set; }
    }
}