// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Data.Models
{
    public partial class HmsMedicine
    {
        public decimal MedicineId { get; set; }
        public string MedicineCode { get; set; }
        public string CategoryCode { get; set; }
        public string MedicineName { get; set; }
        public string ShortName { get; set; }
        public string GenericName { get; set; }
        public string Strength { get; set; }
        public string MedicineDescription { get; set; }
        public string ManufacturerCode { get; set; }
        public string TypeId { get; set; }
        public string BatchNo { get; set; }
        public int? Quantity { get; set; }
        public string UnitId { get; set; }
        public string PackUnitId { get; set; }
        public string PackSize { get; set; }
        public string Weight { get; set; }
        public string WeightUnitId { get; set; }
        public string Uom { get; set; }
        public decimal? SalesPrice { get; set; }
        public string CurrencyId { get; set; }
        public decimal? Vat { get; set; }
        public decimal? PurchasePrice { get; set; }
        public string StorageConditions { get; set; }
        public string PhotoUrl { get; set; }
        public int? ReOrderLevelQty { get; set; }
        public int? MaxOrderQty { get; set; }
        public int? MinOrderQty { get; set; }
        public string ShelfNo { get; set; }
        public string Activity { get; set; }
        public string Remarks { get; set; }
        public string Luser { get; set; }
        public DateTime? Ldate { get; set; }
        public string Lip { get; set; }
        public string Lmac { get; set; }
        public DateTime? ModifyDate { get; set; }
    }
}