// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Data.Models
{
    public partial class HmsNurse
    {
        public string NurseCode { get; set; }
        public int NurseId { get; set; }
        public string NurseName { get; set; }
        public string Email { get; set; }
        public DateTime? DateOfBirth { get; set; }
        public string Phone { get; set; }
        public string CompanyCode { get; set; }
        public string SexCode { get; set; }
        public string ReligionCode { get; set; }
        public string BloodGroupCode { get; set; }
        public string NationalIdNo { get; set; }
        public string DepartmentCode { get; set; }
        public string QualificationCode { get; set; }
        public DateTime? JoiningDate { get; set; }
        public string PresentAddress { get; set; }
        public string PermanentAddress { get; set; }
        public string SpecialityCode { get; set; }
        public decimal? Salary { get; set; }
        public string DesignationCode { get; set; }
        public string ShiftCode { get; set; }
        public string PhotoUrl { get; set; }
        public string DigitalSignatureUrl { get; set; }
        public string ActivityStatus { get; set; }
        public string Luser { get; set; }
        public DateTime? Ldate { get; set; }
        public string Lip { get; set; }
        public string Lmac { get; set; }
        public DateTime? ModifyDate { get; set; }
    }
}