// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Data.Models
{
    public partial class HmsOutPatientPrescription
    {
        public int PrescriptionId { get; set; }
        public string PrescriptionCode { get; set; }
        public DateTime PrescriptionDate { get; set; }
        public string PatientCode { get; set; }
        public string Advice { get; set; }
        public int? VisitingFeeDiscount { get; set; }
        public decimal? VisitingFeeDiscountAmount { get; set; }
        public decimal? VisitingAmount { get; set; }
        public int? ReportShowingFeeDiscount { get; set; }
        public decimal? ReportShowingFeeDiscountAmountt { get; set; }
        public decimal? ReportShowingAmount { get; set; }
        public string ActivityStatus { get; set; }
        public string Luser { get; set; }
        public DateTime? Ldate { get; set; }
        public string Lip { get; set; }
        public string Lmac { get; set; }
        public DateTime? ModifyDate { get; set; }
        public string Bp { get; set; }
        public string Temperature { get; set; }
        public string Pulse { get; set; }
        public string WeightKg { get; set; }
        public string BloodGroup { get; set; }
    }
}