// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Data.Models
{
    public partial class HmsPharmacy
    {
        public decimal AutoId { get; set; }
        public string PharmacyId { get; set; }
        public string PharmacyName { get; set; }
        public string PharmacyMobile { get; set; }
        public string PharmacyEmail { get; set; }
        public string ShortName { get; set; }
        public string Address { get; set; }
        public string Luser { get; set; }
        public DateTime? Ldate { get; set; }
        public string Lip { get; set; }
        public string Lmac { get; set; }
        public DateTime? ModifyDate { get; set; }
        public string CompanyCode { get; set; }
        public string EmployeeId { get; set; }
    }
}