// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Data.Models
{
    public partial class HmsPrescriptionDiagnosis
    {
        public int PrescriptionDiagnosisId { get; set; }
        public string PrescriptionDiagnosisCode { get; set; }
        public string TestChargeCode { get; set; }
        public string PrescriptionCode { get; set; }
        public string Instruction { get; set; }
        public string Luser { get; set; }
        public DateTime? Ldate { get; set; }
        public string Lip { get; set; }
        public string Lmac { get; set; }
        public DateTime? ModifyDate { get; set; }
    }
}