// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Data.Models
{
    public partial class HmsPatientRegistration
    {
        public int PatientId { get; set; }
        public string PatientCode { get; set; }
        public string PatientTypeCode { get; set; }
        public string PatientCategoryCode { get; set; }
        public string RegistrationId { get; set; }
        public DateTime RegistrationDate { get; set; }
        public string PatientName { get; set; }
        public string Email { get; set; }
        public int Age { get; set; }
        public string Phone { get; set; }
        public string CompanyCode { get; set; }
        public string SexCode { get; set; }
        public string ReligionCode { get; set; }
        public string BloodGroupCode { get; set; }
        public string NationalIdNo { get; set; }
        public string EmployeeId { get; set; }
        public string DepartmentCode { get; set; }
        public string DoctorCode { get; set; }
        public DateTime? AdmissionDate { get; set; }
        public string Disease { get; set; }
        public string PresentAddress { get; set; }
        public string PermanentAddress { get; set; }
        public string RoomTypeCode { get; set; }
        public string RoomCode { get; set; }
        public string BedCode { get; set; }
        public string SerialNo { get; set; }
        public decimal? AdvancePayment { get; set; }
        public string PaymentModeCode { get; set; }
        public string PhotoUrl { get; set; }
        public string DigitalSignatureUrl { get; set; }
        public string ActivityStatus { get; set; }
        public bool? IsSendSms { get; set; }
        public string Luser { get; set; }
        public DateTime? Ldate { get; set; }
        public string Lip { get; set; }
        public string Lmac { get; set; }
        public DateTime? ModifyDate { get; set; }
        public string GuardianName { get; set; }
        public string GuardianPhone { get; set; }
        public string ReferenceId { get; set; }
        public string EmergencyPhone { get; set; }
        public string AdmissionTypeId { get; set; }
        public int? AgeYear { get; set; }
        public int? AgeMonth { get; set; }
        public int? AgeDay { get; set; }
        public string SurnameId { get; set; }
        public string FatherHusbandName { get; set; }
        public string RelationCode { get; set; }
        public string PrimaryCareDoctorId { get; set; }
        public string ExpectedLengthStay { get; set; }
    }
}