// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Data.Models
{
    public partial class HmsPatientDischarge
    {
        public int AutoId { get; set; }
        public string DischargeId { get; set; }
        public DateTime DischargeDateTime { get; set; }
        public string DischargeTypeId { get; set; }
        public string PatientCode { get; set; }
        public string RegistrationId { get; set; }
        public string Advice { get; set; }
        public decimal? FinalPayment { get; set; }
        public bool? IsPaid { get; set; }
        public string Remarks { get; set; }
        public string Luser { get; set; }
        public DateTime? Ldate { get; set; }
        public string Lip { get; set; }
        public string Lmac { get; set; }
        public DateTime? ModifyDate { get; set; }
        public string CompanyCode { get; set; }
        public DateTime? FollowUpAppointmentDate { get; set; }
    }
}