// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Data.Models
{
    public partial class HmsReferencePerson
    {
        public decimal AutoId { get; set; }
        public string ReferencePersonId { get; set; }
        public string ReferencePersonName { get; set; }
        public string ReferencePersonMobile { get; set; }
        public string ReferencePersonEmail { get; set; }
        public string Luser { get; set; }
        public DateTime? Ldate { get; set; }
        public string Lip { get; set; }
        public string Lmac { get; set; }
        public DateTime? ModifyDate { get; set; }
        public string CompanyCode { get; set; }
        public string EmployeeId { get; set; }
        public string ReferenceCode { get; set; }
        public string PharmacyId { get; set; }
        public string IsLabTestPatient { get; set; }
    }
}