// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Data.Models
{
    public partial class HmsRoomType
    {
        public string RoomTypeCode { get; set; }
        public int RoomTypeId { get; set; }
        public string RoomTypeName { get; set; }
        public string RoomTypeShortName { get; set; }
        public string RoomFacilities { get; set; }
        public string Luser { get; set; }
        public DateTime? Ldate { get; set; }
        public string Lip { get; set; }
        public string Lmac { get; set; }
        public DateTime? ModifyDate { get; set; }
        public string BanglaShortName { get; set; }
        public string EmployeeId { get; set; }
        public string CompanyCode { get; set; }
    }
}