// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Data.Models
{
    public partial class HmsSpecimen
    {
        public int AutoId { get; set; }
        public string SpecimenId { get; set; }
        public string Specimen { get; set; }
        public string TestCategoryCode { get; set; }
        public string TestChargeCode { get; set; }
        public string Luser { get; set; }
        public DateTime? Ldate { get; set; }
        public string Lip { get; set; }
        public string Lmac { get; set; }
        public DateTime? ModifyDate { get; set; }
        public string CompanyCode { get; set; }
        public string RoomNo { get; set; }
        public string TestSubCategoryCode { get; set; }
    }
}