// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Data.Models
{
    public partial class HmsTestEntry
    {
        public int AutoId { get; set; }
        public string LabTestNo { get; set; }
        public DateTime LabTestDateTime { get; set; }
        public string Mrno { get; set; }
        public DateTime MrdateTime { get; set; }
        public string PatientCode { get; set; }
        public string RegistrationId { get; set; }
        public decimal? TotalAmount { get; set; }
        public decimal? DiscountPercent { get; set; }
        public decimal? DiscountAmount { get; set; }
        public decimal? Payable { get; set; }
        public decimal? Received { get; set; }
        public decimal? Due { get; set; }
        public string DiscountPermittedBy { get; set; }
        public string Remarks { get; set; }
        public string PreparedBy { get; set; }
        public string Luser { get; set; }
        public DateTime? Ldate { get; set; }
        public string Lip { get; set; }
        public string Lmac { get; set; }
        public DateTime? ModifyDate { get; set; }
        public string CompanyCode { get; set; }
        public DateTime? DuePaymentDate { get; set; }
        public string DuePaymentModeId { get; set; }
        public decimal? DueReceived { get; set; }
        public bool? IsPaid { get; set; }
        public decimal? Less { get; set; }
        public string Notes { get; set; }
        public string IsApproved { get; set; }
        public string ApprovedEmployeeId { get; set; }
        public DateTime? ApprovedDateTime { get; set; }
    }
}