// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Data.Models
{
    public partial class HmsTestCharge
    {
        public string TestChargeCode { get; set; }
        public int TestChargeId { get; set; }
        public string TestChargeName { get; set; }
        public string TestCategoryCode { get; set; }
        public string TestSubCategoryCode { get; set; }
        public string TestChargeShortName { get; set; }
        public decimal Amount { get; set; }
        public string Luser { get; set; }
        public DateTime? Ldate { get; set; }
        public string Lip { get; set; }
        public string Lmac { get; set; }
        public DateTime? ModifyDate { get; set; }
        public string BanglaShortName { get; set; }
        public string EmployeeId { get; set; }
        public string CompanyCode { get; set; }
        public int? DeliveryTime { get; set; }
        public string DeliveryPeriodId { get; set; }
        public string SpecimenId { get; set; }
        public string CarriedOutById { get; set; }
    }
}