// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Data.Models
{
    public partial class HmsTestEntryDetails
    {
        public int LabTestDetailsId { get; set; }
        public string LabTestNo { get; set; }
        public string TestCategoryCode { get; set; }
        public string TestChargeCode { get; set; }
        public DateTime? DeliveryDate { get; set; }
        public decimal? Amount { get; set; }
        public decimal? DiscountPercent { get; set; }
        public decimal? DiscountAmount { get; set; }
        public decimal? AfterDiscountAmount { get; set; }
        public string Luser { get; set; }
        public string TestSubCategoryCode { get; set; }
    }
}