// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Data.Models
{
    public partial class HrmAtdLeaveType
    {
        public decimal AutoId { get; set; }
        public string LeaveTypeCode { get; set; }
        public string Name { get; set; }
        public string ShortName { get; set; }
        public string RulePolicy { get; set; }
        public decimal NoOfDay { get; set; }
        public decimal For { get; set; }
        public string Ymwd { get; set; }
        public DateTime Wef { get; set; }
        public string Luser { get; set; }
        public DateTime? Ldate { get; set; }
        public string Lip { get; set; }
        public string Lmac { get; set; }
        public DateTime? ModifyDate { get; set; }
    }
}