// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Data.Models
{
    public partial class HrmAppointedEmployeeEntry
    {
        public decimal AutoId { get; set; }
        public string Aeid { get; set; }
        public string EmployeeName { get; set; }
        public string FatherName { get; set; }
        public string MotherName { get; set; }
        public string SexCode { get; set; }
        public string MobileNumber { get; set; }
        public string Address { get; set; }
        public string DesignationCode { get; set; }
        public DateTime? JoiningDate { get; set; }
        public decimal? GrossSalary { get; set; }
        public decimal? MobileAllowance { get; set; }
        public string ProbationPeriod { get; set; }
        public string ProbationPeriodType { get; set; }
        public string Luser { get; set; }
        public DateTime? Ldate { get; set; }
        public string Lip { get; set; }
        public string Lmac { get; set; }
        public DateTime? ModifyDate { get; set; }
        public string CompanyCode { get; set; }
        public string EntryUserEmployeeId { get; set; }
        public string EmployeeId { get; set; }
    }
}