// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Data.Models
{
    public partial class HrmAtdMachineData
    {
        public decimal AutoId { get; set; }
        public string FingerPrintId { get; set; }
        public string MachineId { get; set; }
        public DateTime Date { get; set; }
        public DateTime Time { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public string Hoalr { get; set; }
    }
}