// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Data.Models
{
    public partial class HrmDefBankAndNomineeInfo
    {
        public decimal AutoId { get; set; }
        public string BankAndNomineeId { get; set; }
        public string EmployeeId { get; set; }
        public string BankId { get; set; }
        public string BankBranchId { get; set; }
        public string BankAccountName { get; set; }
        public string BankAccountNo { get; set; }
        public string AtmcardNo { get; set; }
        public string NomineeName { get; set; }
        public string Relation { get; set; }
        public string PresentAddress { get; set; }
        public string ParmanentAddress { get; set; }
        public string Luser { get; set; }
        public DateTime? Ldate { get; set; }
        public string Lip { get; set; }
        public string Lmac { get; set; }
        public DateTime? ModifyDate { get; set; }
        public string CompanyCode { get; set; }
        public string EmployeeId2 { get; set; }
    }
}