// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Data.Models
{
    public partial class HrmDefProbationPeriodExtension
    {
        public decimal AutoId { get; set; }
        public string Ppeid { get; set; }
        public string EmployeeId { get; set; }
        public string ExtendedPeriod { get; set; }
        public string PeriodInfoId { get; set; }
        public DateTime? Wef { get; set; }
        public decimal? PreviousSalary { get; set; }
        public decimal? ExtensionSalary { get; set; }
        public decimal? CurrentSalary { get; set; }
        public string RefLetterNo { get; set; }
        public DateTime? RefLetterDate { get; set; }
        public string Remarks { get; set; }
        public string Luser { get; set; }
        public DateTime? Ldate { get; set; }
        public string Lip { get; set; }
        public string Lmac { get; set; }
        public DateTime? ModifyDate { get; set; }
        public string CompanyCode { get; set; }
        public string UserEmployeeId { get; set; }
    }
}