// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Data.Models
{
    public partial class HrmDefGrade
    {
        public decimal AutoId { get; set; }
        public string GradeCode { get; set; }
        public string GradeName { get; set; }
        public string GradeShortName { get; set; }
        public decimal? FromGrossSalary { get; set; }
        public decimal? ToGrossSalary { get; set; }
        public string GradeTypeId { get; set; }
        public string Luser { get; set; }
        public DateTime? Ldate { get; set; }
        public string Lip { get; set; }
        public string Lmac { get; set; }
        public DateTime? ModifyDate { get; set; }
    }
}