// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Data.Models
{
    public partial class HrmDefDesignation
    {
        public decimal AutoId { get; set; }
        public string DesignationCode { get; set; }
        public string DesignationName { get; set; }
        public string DesignationShortName { get; set; }
        public string GradeCode { get; set; }
        public string Luser { get; set; }
        public DateTime? Ldate { get; set; }
        public string Lip { get; set; }
        public string Lmac { get; set; }
        public DateTime? ModifyDate { get; set; }
        public string BanglaDesignation { get; set; }
        public string BanglaShortName { get; set; }
        public string StepNoId { get; set; }
        public string CompanyCode { get; set; }
        public string EmployeeId { get; set; }
        public string MobileAllowanceId { get; set; }
    }
}