// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Data.Models
{
    public partial class HrmDefOvertimeRule
    {
        public decimal AutoId { get; set; }
        public string OvertimeRuleId { get; set; }
        public string OvertimeRuleName { get; set; }
        public int? OtgraceTime { get; set; }
        public decimal? MaxOtperDay { get; set; }
        public int? MinOtminutes { get; set; }
        public string WeeklyOffOtrule { get; set; }
        public string HolidayOtrule { get; set; }
        public string Luser { get; set; }
        public DateTime? Ldate { get; set; }
        public string Lip { get; set; }
        public string Lmac { get; set; }
        public DateTime? ModifyDate { get; set; }
    }
}