// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Data.Models
{
    public partial class HrmEmployeeDocumentInfo
    {
        public decimal AutoId { get; set; }
        public string EmpDocId { get; set; }
        public string EmployeeId { get; set; }
        public string DocumentName { get; set; }
        public string DocumentDiscription { get; set; }
        public string DocumentType { get; set; }
        public string Doucment { get; set; }
        public string Luser { get; set; }
        public DateTime? Ldate { get; set; }
        public string Lip { get; set; }
        public string Lmac { get; set; }
        public DateTime? ModifyDate { get; set; }
        public string CompanyCode { get; set; }
        public string UserInfoEmployeeId { get; set; }
        public string BranchCode { get; set; }
    }
}