// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Data.Models
{
    public partial class HrmEmployeeContactInfo
    {
        public decimal AutoId { get; set; }
        public string EmpContactId { get; set; }
        public string EmployeeId { get; set; }
        public string ParmanentAddress { get; set; }
        public string ParmanentPostOffice { get; set; }
        public string ParmanentThana { get; set; }
        public string ParmanentPostCode { get; set; }
        public string ParmanentDistrict { get; set; }
        public string ParmanentPhone { get; set; }
        public string PresentAddress { get; set; }
        public string PresentPostOffice { get; set; }
        public string PresentThana { get; set; }
        public string PresentPostCode { get; set; }
        public string PresentDistrict { get; set; }
        public string PresentMobile { get; set; }
        public string PresentPhone { get; set; }
        public string PresentFax { get; set; }
        public string PresentEmail { get; set; }
        public string EmContactName1 { get; set; }
        public string EmContactRelation1 { get; set; }
        public string EmContactAddress1 { get; set; }
        public string EmContactPhone1 { get; set; }
        public string EmContactMobile1 { get; set; }
        public string EmContactFax1 { get; set; }
        public string EmContactEmail { get; set; }
        public string EmContactName2 { get; set; }
        public string EmContactRelation2 { get; set; }
        public string EmContactAddress2 { get; set; }
        public string EmContactPhone2 { get; set; }
        public string EmContactMobile2 { get; set; }
        public string EmContactFax2 { get; set; }
        public string EmContactEmai2 { get; set; }
        public string Luser { get; set; }
        public DateTime? Ldate { get; set; }
        public string Lip { get; set; }
        public string Lmac { get; set; }
        public DateTime? ModifyDate { get; set; }
        public string CompanyCode { get; set; }
        public string UserInfoEmployeeId { get; set; }
        public string ParmanentAddressBangla { get; set; }
        public string PresentAddressBangla { get; set; }
        public string BranchCode { get; set; }
    }
}