// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Data.Models
{
    public partial class HrmEmployeeReferenceInfo
    {
        public decimal AutoId { get; set; }
        public string EmpReferenceId { get; set; }
        public string EmployeeId { get; set; }
        public string ReferenceName { get; set; }
        public string OrganizationName { get; set; }
        public string Designation { get; set; }
        public string RefAddress { get; set; }
        public string RelationId { get; set; }
        public string MobileNumber { get; set; }
        public string PhoneNumber { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public string Luser { get; set; }
        public DateTime? Ldate { get; set; }
        public string Lip { get; set; }
        public string Lmac { get; set; }
        public DateTime? ModifyDate { get; set; }
        public string CompanyCode { get; set; }
        public string UserInfoEmployeeId { get; set; }
        public string NationalityCode { get; set; }
        public string BranchCode { get; set; }
    }
}