// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Data.Models
{
    public partial class HrmEmployeeExp
    {
        public decimal AutoId { get; set; }
        public string EmpExpId { get; set; }
        public string EmployeeId { get; set; }
        public string CompanyNameId { get; set; }
        public string BusinessType { get; set; }
        public string Address { get; set; }
        public string DepartmentId { get; set; }
        public string DesignationId { get; set; }
        public string Responsibilities { get; set; }
        public string JobNatureId { get; set; }
        public DateTime FromDate { get; set; }
        public DateTime ToDate { get; set; }
        public decimal Salary { get; set; }
        public string Remarks { get; set; }
        public string Luser { get; set; }
        public DateTime? Ldate { get; set; }
        public string Lip { get; set; }
        public string Lmac { get; set; }
        public DateTime? ModifyDate { get; set; }
        public string CompanyCode { get; set; }
        public string UserInfoEmployeeId { get; set; }
    }
}