// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Data.Models
{
    public partial class HrmEmployeeEducation
    {
        public decimal AutoId { get; set; }
        public string EmpEduCode { get; set; }
        public string EmployeeId { get; set; }
        public string DegreeCode { get; set; }
        public string ExamTitleCode { get; set; }
        public string InstitueCode { get; set; }
        public string BoardCode { get; set; }
        public string GroupCode { get; set; }
        public string ResultDivision { get; set; }
        public string CgpaMarks { get; set; }
        public string ScaleOf { get; set; }
        public string YearofPasssing { get; set; }
        public string Dueration { get; set; }
        public string DuratioinType { get; set; }
        public string Achievment { get; set; }
        public string Remarks { get; set; }
        public string Luser { get; set; }
        public DateTime? Ldate { get; set; }
        public string Lip { get; set; }
        public string Lmac { get; set; }
        public DateTime? ModifyDate { get; set; }
        public string CompanyCode { get; set; }
        public string BranchCode { get; set; }
    }
}