// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Data.Models
{
    public partial class HrmEmployeeLetters
    {
        public decimal AutoId { get; set; }
        public string LetterNo { get; set; }
        public string RefNo { get; set; }
        public string LetterTypeId { get; set; }
        public string EmployeeId { get; set; }
        public DateTime? AppliedDate { get; set; }
        public string Luser { get; set; }
        public DateTime? Ldate { get; set; }
        public string Lip { get; set; }
        public string Lmac { get; set; }
        public DateTime? ModifyDate { get; set; }
        public string CompanyCode { get; set; }
        public string EntryUserEmployeeId { get; set; }
        public string Nocid { get; set; }
    }
}