// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Data.Models
{
    public partial class HrmEmployeeFamily
    {
        public decimal AutoId { get; set; }
        public string EmpFamilyId { get; set; }
        public string EmployeeId { get; set; }
        public string RelationshipId { get; set; }
        public string Name { get; set; }
        public string OccupationId { get; set; }
        public string BloodGroupId { get; set; }
        public DateTime DateOfBirth { get; set; }
        public string AddressDetails { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string Luser { get; set; }
        public DateTime? Ldate { get; set; }
        public string Lip { get; set; }
        public string Lmac { get; set; }
        public DateTime? ModifyDate { get; set; }
        public string CompanyCode { get; set; }
        public string UserInfoEmployeeId { get; set; }
        public string BranchCode { get; set; }
    }
}