// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Data.Models
{
    public partial class HrmEmployeeAdditionalInfo
    {
        public decimal AutoId { get; set; }
        public string EmployeAddInfoId { get; set; }
        public string EmployeeId { get; set; }
        public string PassportNo { get; set; }
        public string PassportPlaceOfIssue { get; set; }
        public DateTime? PassportIssueDate { get; set; }
        public DateTime? PassportExpiryDate { get; set; }
        public string SalaryBankId { get; set; }
        public string SalaryBranchId { get; set; }
        public string BranchAddres { get; set; }
        public string BankAcname { get; set; }
        public string BankAcNo { get; set; }
        public string AtmCardNo { get; set; }
        public string LicenseNo { get; set; }
        public string LicenseType { get; set; }
        public DateTime? LicenseIssueDate { get; set; }
        public DateTime? LicenseExpireDate { get; set; }
        public string SymbolOfVehicleClass { get; set; }
        public string LicensePlaceOfIssue { get; set; }
        public string WorkPermitNo { get; set; }
        public string WorkPermitType { get; set; }
        public DateTime? WpEffectiveDate { get; set; }
        public DateTime? WpExpireDate { get; set; }
        public string Luser { get; set; }
        public DateTime? Ldate { get; set; }
        public string Lip { get; set; }
        public string Lmac { get; set; }
        public DateTime? ModifyDate { get; set; }
        public string CompanyCode { get; set; }
        public string UserInfoEmployeeId { get; set; }
        public string PassportName { get; set; }
        public string BranchCode { get; set; }
        public string BankIducbl { get; set; }
        public string BankBranchIducbl { get; set; }
        public string BranchAddressUcbl { get; set; }
        public string BankAcNameUcbl { get; set; }
        public string BankAcNoUcbl { get; set; }
        public string BankAcNoSibl { get; set; }
        public string BankIdsibl { get; set; }
        public string BankBranchIdsibl { get; set; }
        public string BranchAddressSibl { get; set; }
        public string BankAcNameSibl { get; set; }
    }
}