// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Data.Models
{
    public partial class HrmEmployee
    {
        public decimal AutoId { get; set; }
        public string EmployeeId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string FatherName { get; set; }
        public string MotherName { get; set; }
        public DateTime? DateOfBirthCertificate { get; set; }
        public DateTime? DateOfBirthOrginal { get; set; }
        public string BirthCertificateNo { get; set; }
        public string PlaceOfBirth { get; set; }
        public string SexCode { get; set; }
        public string BloodGroupCode { get; set; }
        public string NationalityCode { get; set; }
        public string NationalIdno { get; set; }
        public string ReligionCode { get; set; }
        public string MaritalStatusCode { get; set; }
        public DateTime? MarriageDate { get; set; }
        public string NoOfSon { get; set; }
        public string NoOfDaughters { get; set; }
        public string CardNo { get; set; }
        public string Luser { get; set; }
        public DateTime? Ldate { get; set; }
        public string Lip { get; set; }
        public string Lmac { get; set; }
        public DateTime? ModifyDate { get; set; }
        public string CompanyCode { get; set; }
        public string UserInfoEmployeeId { get; set; }
        public string PersonalEmail { get; set; }
        public string Telephone { get; set; }
        public string TinNo { get; set; }
        public string ExtraCurriActivities { get; set; }
        public string Remarks { get; set; }
        public string FirstNameBangla { get; set; }
        public string LastNameBangla { get; set; }
        public string BranchCode { get; set; }
        public string FathersOccupation { get; set; }
        public string MothersOccupation { get; set; }
        public string Spouse { get; set; }
    }
}