// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Data.Models
{
    public partial class HrmEisReposition
    {
        public decimal Tc { get; set; }
        public string RepositionId { get; set; }
        public string EmployeeId { get; set; }
        public string Type { get; set; }
        public string Year { get; set; }
        public DateTime Wef { get; set; }
        public string RefLetterNo { get; set; }
        public DateTime RefLetterDate { get; set; }
        public string Remark { get; set; }
        public string PreCompanyCode2 { get; set; }
        public string PreBranchCode { get; set; }
        public string PreDivisionCode { get; set; }
        public string PreDepartmentCode { get; set; }
        public string PreSectionCode { get; set; }
        public string PreLineCode { get; set; }
        public string PreDesignationCode { get; set; }
        public string PreLocationCode { get; set; }
        public string CurrCompanyCode2 { get; set; }
        public string CurrBranchCode { get; set; }
        public string CurrDivisionCode { get; set; }
        public string CurrDepartmentCode { get; set; }
        public string CurrSectionCode { get; set; }
        public string CurrLineCode { get; set; }
        public string CurrDesignationCode { get; set; }
        public string CurrLocationCode { get; set; }
        public string Luser { get; set; }
        public DateTime? Ldate { get; set; }
        public string Lip { get; set; }
        public string Lmac { get; set; }
        public DateTime? ModifyDate { get; set; }
        public string CompanyCode { get; set; }
        public string MonthName { get; set; }
        public decimal? PromotionAmount { get; set; }
        public decimal? PreviousSalary { get; set; }
        public decimal? CurrentSalary { get; set; }
        public decimal? PreExpatriateBasicSalary { get; set; }
        public decimal? CurrExpatriateBasicSalary { get; set; }
        public decimal? PreExpatriateHouseRent { get; set; }
        public decimal? CurrExpatriateHouseRent { get; set; }
        public decimal? PreExpatriateConveyance { get; set; }
        public decimal? CurrExpatriateConveyance { get; set; }
        public decimal? PreExpatriateMedical { get; set; }
        public decimal? CurrExpatriateMedical { get; set; }
        public decimal? PreExpatriateFcp { get; set; }
        public decimal? CurrExpatriateFcp { get; set; }
        public string PreGradeCode { get; set; }
        public string CurrentGradeCode { get; set; }
    }
}