// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Data.Models
{
    public partial class HrmEmployeeOfficialInfo
    {
        public decimal AutoId { get; set; }
        public string EmployeeId { get; set; }
        public string CompanyCode { get; set; }
        public string BranchCode { get; set; }
        public string DivisionCode { get; set; }
        public string DepartmentCode { get; set; }
        public string DesignationCode { get; set; }
        public string EmpTypeCode { get; set; }
        public string GradeCode { get; set; }
        public string EmploymentNatureId { get; set; }
        public decimal GrossSalary { get; set; }
        public string CurrencyCode { get; set; }
        public string PaymentPeriodId { get; set; }
        public string DisbursementMethodId { get; set; }
        public string ShiftCode { get; set; }
        public string EmployeeStatus { get; set; }
        public string ReportingTo { get; set; }
        public string Hod { get; set; }
        public string MobileNo { get; set; }
        public string Email { get; set; }
        public string AppointmentLetterNo { get; set; }
        public DateTime? AppointmentLetterDate { get; set; }
        public DateTime? JoiningDate { get; set; }
        public decimal JoiningSalary { get; set; }
        public string ProbationPeriodType { get; set; }
        public string ProbationPeriod { get; set; }
        public DateTime? ConfirmeDate { get; set; }
        public string Luser { get; set; }
        public DateTime? Ldate { get; set; }
        public string Lip { get; set; }
        public string Lmac { get; set; }
        public DateTime? ModifyDate { get; set; }
        public string CompanyCodeSession { get; set; }
        public string UserInfoEmployeeId { get; set; }
        public string StepNoId { get; set; }
        public string TecnicalSkillTypeId { get; set; }
        public string SalaryScaleId { get; set; }
        public DateTime? ContractEndDate { get; set; }
        public string SectionCode { get; set; }
        public string LineCode { get; set; }
        public string AttendenceId { get; set; }
        public string IsExpatriate { get; set; }
        public decimal? ExpatriateBasicSalary { get; set; }
        public decimal? ExpatriateHouseRent { get; set; }
        public decimal? ExpatriateConveyance { get; set; }
        public decimal? ExpatriateMedical { get; set; }
        public decimal? Lfa { get; set; }
        public decimal? MobileAllowance { get; set; }
        public string ConfirmationRefNo { get; set; }
        public DateTime? ProbationEffectDate { get; set; }
        public decimal? ModeOfPaymentInBankPercentage { get; set; }
        public string IsLunchBilEligible { get; set; }
        public string IsOverTimeEligible { get; set; }
        public string IsExtraDutyEligible { get; set; }
        public string IsGovtHolidayEligible { get; set; }
        public string IsAttendanceBonusEligible { get; set; }
        public string PayId { get; set; }
        public string ClientId { get; set; }
    }
}