// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Data.Models
{
    public partial class HrmEmpDigitalSignature
    {
        public int AutoId { get; set; }
        public string EmployeeId { get; set; }
        public byte[] DigitalSignature { get; set; }
        public string ImgType { get; set; }
        public long ImgSize { get; set; }
    }
}