// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Data.Models
{
    public partial class HrmHomeOfficeRequest
    {
        public decimal Tc { get; set; }
        public string Horid { get; set; }
        public string EmployeeId { get; set; }
        public string HodemployeeId { get; set; }
        public DateTime? RequestDate { get; set; }
        public DateTime? StartDate { get; set; }
        public DateTime? EndDate { get; set; }
        public string Reason { get; set; }
        public string ApprovalStatus { get; set; }
        public string ApprovedBy { get; set; }
        public DateTime? ApprovalDatetime { get; set; }
        public string Remarks { get; set; }
        public string ApprovalStatusHr { get; set; }
        public string ApprovedByHr { get; set; }
        public DateTime? ApprovalDatetimeHr { get; set; }
        public string Hrremarks { get; set; }
        public string Luser { get; set; }
        public DateTime? Ldate { get; set; }
        public string Lip { get; set; }
        public string Lmac { get; set; }
        public DateTime? ModifyDate { get; set; }
        public string CompanyCode { get; set; }
        public string EntryBy { get; set; }
    }
}