// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Data.Models
{
    public partial class HrmItemMasterInformation
    {
        public decimal AutoId { get; set; }
        public string ProductCode { get; set; }
        public string ProductName { get; set; }
        public string Description { get; set; }
        public string UnitId { get; set; }
        public decimal? PurchaseCost { get; set; }
        public string Luser { get; set; }
        public DateTime? Ldate { get; set; }
        public string Lip { get; set; }
        public string Lmac { get; set; }
        public DateTime? ModifyDate { get; set; }
        public string UserInfoEmployeeId { get; set; }
        public string CompanyCode { get; set; }
        public string CatagoryId { get; set; }
        public string BrandId { get; set; }
    }
}