// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Data.Models
{
    public partial class HrmIncrement
    {
        public decimal Tc { get; set; }
        public string IncrementId { get; set; }
        public string EmployeeId { get; set; }
        public string Year { get; set; }
        public decimal PreviousSalary { get; set; }
        public decimal IncAmount { get; set; }
        public decimal PresentSalary { get; set; }
        public DateTime Wef { get; set; }
        public string IncLetterNo { get; set; }
        public DateTime IncLetterDate { get; set; }
        public string Remark { get; set; }
        public string Luser { get; set; }
        public DateTime? Ldate { get; set; }
        public string Lip { get; set; }
        public string Lmac { get; set; }
        public DateTime? ModifyDate { get; set; }
        public string CompanyCode { get; set; }
        public string IncType { get; set; }
        public string MonthName { get; set; }
        public decimal? PreExpatriateBasicSalary { get; set; }
        public decimal? CurrExpatriateBasicSalary { get; set; }
        public decimal? PreExpatriateHouseRent { get; set; }
        public decimal? CurrExpatriateHouseRent { get; set; }
        public decimal? PreExpatriateConveyance { get; set; }
        public decimal? CurrExpatriateConveyance { get; set; }
        public decimal? PreExpatriateMedical { get; set; }
        public decimal? CurrExpatriateMedical { get; set; }
        public decimal? PreExpatriateFcp { get; set; }
        public decimal? CurrExpatriateFcp { get; set; }
    }
}