// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Data.Models
{
    public partial class HrmLeaveApplicationDays
    {
        public decimal AutoId { get; set; }
        public string LeaveAppEntryId { get; set; }
        public DateTime Days { get; set; }
    }
}