// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Data.Models
{
    public partial class HrmLeaveApplicationEntry
    {
        public decimal AutoId { get; set; }
        public string LeaveAppEntryId { get; set; }
        public string EmployeeId { get; set; }
        public string LeaveTypeId { get; set; }
        public DateTime StartDate { get; set; }
        public DateTime EndDate { get; set; }
        public decimal NoOfDay { get; set; }
        public string HalfDay { get; set; }
        public string FirstOrSecondHalf { get; set; }
        public string Reason { get; set; }
        public string BossEmpAutoId { get; set; }
        public string Hod { get; set; }
        public string IsApproved { get; set; }
        public string Luser { get; set; }
        public DateTime? Ldate { get; set; }
        public string Lip { get; set; }
        public string Lmac { get; set; }
        public DateTime? ModifyDate { get; set; }
        public string ConfirmationRemarks { get; set; }
        public string CompanyCode { get; set; }
        public string HodapprovalStatus { get; set; }
        public string HodapprovalRemarks { get; set; }
        public string HrapprovalStatus { get; set; }
        public string HrapprovalRemarks { get; set; }
        public string ApplyLeaveFormat { get; set; }
        public DateTime? ShortLeaveFrom { get; set; }
        public DateTime? ShortLeaveTo { get; set; }
        public TimeOnly? ShortLeaveTime { get; set; }
        public string LeaveApplyProcess { get; set; }
        public string SickLeaveFilePath { get; set; }
    }
}