// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Data.Models
{
    public partial class HrmNocinfo
    {
        public decimal AutoId { get; set; }
        public string Nocid { get; set; }
        public string NoctypeId { get; set; }
        public string EmployeeId { get; set; }
        public string PlaceofVisit { get; set; }
        public DateTime? FromDate { get; set; }
        public DateTime? ToDate { get; set; }
        public string UniversityName { get; set; }
        public string CourseName { get; set; }
        public string Remarks { get; set; }
        public string Luser { get; set; }
        public DateTime? Ldate { get; set; }
        public string Lip { get; set; }
        public string Lmac { get; set; }
        public DateTime? ModifyDate { get; set; }
        public string CompanyCode { get; set; }
        public string UserEmployeeId { get; set; }
    }
}