// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Data.Models
{
    public partial class HrmPayrollLoan
    {
        public decimal AutoId { get; set; }
        public string LoanId { get; set; }
        public string EmployeeId { get; set; }
        public DateTime? LoanDate { get; set; }
        public string LoanTypeId { get; set; }
        public DateTime? StartDate { get; set; }
        public DateTime? EndDate { get; set; }
        public decimal? LoanAmount { get; set; }
        public string NoOfInstallment { get; set; }
        public decimal? MonthlyDeduction { get; set; }
        public string PayHeadNameId { get; set; }
        public string PaymentModeId { get; set; }
        public string ChequeNo { get; set; }
        public DateTime? ChequeDate { get; set; }
        public string BankId { get; set; }
        public string BankAccount { get; set; }
        public string Remarks { get; set; }
        public string Luser { get; set; }
        public DateTime? Ldate { get; set; }
        public string Lip { get; set; }
        public string Lmac { get; set; }
        public DateTime? ModifyDate { get; set; }
        public string CompanyCode { get; set; }
        public string ReasonOfLoanTaken { get; set; }
        public string LoanStatus { get; set; }
    }
}