// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Data.Models
{
    public partial class HrmPayMonth
    {
        public byte MonthId { get; set; }
        public string MonthName { get; set; }
        public byte MonthNum { get; set; }
        public string MonthNameBangla { get; set; }
    }
}