// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Data.Models
{
    public partial class HrmPayEmployeesRequiredInvestmentDetailsTemp
    {
        public decimal Tc { get; set; }
        public string Eridid { get; set; }
        public string Eriid { get; set; }
        public string InvestmentHeadId { get; set; }
        public decimal? Amount { get; set; }
        public string Remarks { get; set; }
        public string Luser { get; set; }
    }
}