// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Data.Models
{
    public partial class HrmPayInvestmentHeadEntry
    {
        public int Tc { get; set; }
        public string InvestmentHeadId { get; set; }
        public string InvestmentHead { get; set; }
        public string ShortName { get; set; }
        public string Luser { get; set; }
        public DateTime? Ldate { get; set; }
        public string Lip { get; set; }
        public string Lmac { get; set; }
        public DateTime? ModifyDate { get; set; }
        public string CompanyCode { get; set; }
        public string EntryUserEmployeeId { get; set; }
    }
}