// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Data.Models
{
    public partial class HrmPayrollPaymentReceive
    {
        public decimal AutoId { get; set; }
        public string PaymentId { get; set; }
        public DateTime? PaymentDate { get; set; }
        public string EmployeeId { get; set; }
        public string LoanId { get; set; }
        public decimal? PaymentAmount { get; set; }
        public string PaymentModeId { get; set; }
        public string ChequeNo { get; set; }
        public DateTime? ChequeDate { get; set; }
        public string BankId { get; set; }
        public string BankAccount { get; set; }
        public string Remarks { get; set; }
        public string Luser { get; set; }
        public DateTime? Ldate { get; set; }
        public string Lip { get; set; }
        public string Lmac { get; set; }
        public DateTime? ModifyDate { get; set; }
        public string CompanyCode { get; set; }
        public string EntryUserId { get; set; }
    }
}