// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Data.Models
{
    public partial class HrmPayAdvancePay
    {
        public decimal AdvancePayCode { get; set; }
        public string AdvancePayId { get; set; }
        public string EmployeeId { get; set; }
        public string AdvanceAdjustStatus { get; set; }
        public decimal AdvanceAmount { get; set; }
        public decimal MonthlyDeduction { get; set; }
        public string SalaryMonth { get; set; }
        public string SalaryYear { get; set; }
        public string NoOfPaymentInstallment { get; set; }
        public string PayHeadNameId { get; set; }
        public string Remarks { get; set; }
        public string Luser { get; set; }
        public DateTime? Ldate { get; set; }
        public string Lip { get; set; }
        public string Lmac { get; set; }
        public DateTime? ModifyDate { get; set; }
        public string CompanyCode { get; set; }
        public string AdjustmentType { get; set; }
        public string LoanId { get; set; }
    }
}