// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Data.Models
{
    public partial class HrmPayExcessTdsforLastIncomeYearEntry
    {
        public decimal AutoId { get; set; }
        public string Etdsliyid { get; set; }
        public string EmployeeId { get; set; }
        public decimal Tdsamount { get; set; }
        public string SalaryMonth { get; set; }
        public string SalaryYear { get; set; }
        public string ApprovedStatus { get; set; }
        public string Remark { get; set; }
        public string Luser { get; set; }
        public DateTime? Ldate { get; set; }
        public string Lip { get; set; }
        public string Lmac { get; set; }
        public DateTime? ModifyDate { get; set; }
        public string CompanyCode { get; set; }
        public string FinancialCodeNo { get; set; }
        public DateTime? EffectiveDate { get; set; }
        public string IsfullAmountAdjust { get; set; }
    }
}