// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Data.Models
{
    public partial class HrmPayTaxAdjustmentEntry
    {
        public decimal TaxAdjustmentCode { get; set; }
        public string TaxAdjustmentId { get; set; }
        public string EmployeeId { get; set; }
        public decimal TaxDeductionAmount { get; set; }
        public string SalaryMonth { get; set; }
        public string SalaryYear { get; set; }
        public string ApprovedStatus { get; set; }
        public string Remark { get; set; }
        public string Luser { get; set; }
        public DateTime? Ldate { get; set; }
        public string Lip { get; set; }
        public string Lmac { get; set; }
        public DateTime? ModifyDate { get; set; }
        public string CompanyCode { get; set; }
        public string NoOfMonths { get; set; }
    }
}