// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Data.Models
{
    public partial class HrmPaySalaryData
    {
        public decimal Tc { get; set; }
        public string EmployeeId { get; set; }
        public string GradeName { get; set; }
        public string BranchCode { get; set; }
        public string DivisionCode { get; set; }
        public string DepartmentCode { get; set; }
        public string CompanyCode { get; set; }
        public string JoiningDate { get; set; }
        public string EmploymentDuration { get; set; }
        public string DaysOfTheMonth { get; set; }
        public string WorkingDays { get; set; }
        public decimal? GrossSalary { get; set; }
        public decimal? BasicSalary { get; set; }
        public decimal? Increment { get; set; }
        public decimal? GrossAfterIncrement { get; set; }
        public decimal? HouseRent { get; set; }
        public decimal? Medical { get; set; }
        public decimal? Conveyance { get; set; }
        public decimal? Wfood { get; set; }
        public decimal? SpecialAllow { get; set; }
        public decimal? Allowance40PercentOfGross { get; set; }
        public decimal? SalaryEarned { get; set; }
        public int? AttenBonus { get; set; }
        public int? OthersBenefits { get; set; }
        public decimal? Incentive { get; set; }
        public decimal? Ot { get; set; }
        public decimal? Otrate { get; set; }
        public decimal? Otamount { get; set; }
        public decimal? ExtraDutyDay { get; set; }
        public decimal? ExtraDutyRate { get; set; }
        public decimal? ExtraDutyAmount { get; set; }
        public decimal? TotalEarned { get; set; }
        public decimal? ExtraGrossSalary { get; set; }
        public decimal? MobileBill { get; set; }
        public int? Present { get; set; }
        public int? Late { get; set; }
        public int? Cl { get; set; }
        public int? Sl { get; set; }
        public int? El { get; set; }
        public int? Ml { get; set; }
        public int? Spl { get; set; }
        public int? Weekend { get; set; }
        public int? Holiday { get; set; }
        public int? Absent { get; set; }
        public decimal? TotalLeave { get; set; }
        public int? LeaveAllowed { get; set; }
        public int? TotalDays { get; set; }
        public int? LateCount { get; set; }
        public int? TotalDeductionDays { get; set; }
        public int? NetPayableDays { get; set; }
        public decimal? LateDeduction { get; set; }
        public decimal? AdvanceDeduction { get; set; }
        public decimal? Pf { get; set; }
        public int? StampDeduction { get; set; }
        public decimal? Lunch { get; set; }
        public decimal? Tds { get; set; }
        public decimal? MobAndInt { get; set; }
        public decimal? Transport { get; set; }
        public decimal? Insurance { get; set; }
        public decimal? Penalty { get; set; }
        public decimal? Other { get; set; }
        public decimal? Food { get; set; }
        public decimal? TotalDeductionOpen { get; set; }
        public decimal? ArrearSalary { get; set; }
        public decimal? NetSalary { get; set; }
        public decimal? CashOrChequePayablePercentage { get; set; }
        public decimal? CashOrChequePayableAmount { get; set; }
        public decimal? BankPayableAmount { get; set; }
        public decimal? PreviousMonth { get; set; }
        public decimal? Difference { get; set; }
        public string ModeOfPayment { get; set; }
        public string CompanyName { get; set; }
        public string DisbursementMethod { get; set; }
        public string BankAcname { get; set; }
        public string BankAcNo { get; set; }
        public string BankName { get; set; }
        public string BankBranchName { get; set; }
        public string MonthName { get; set; }
        public int? YearName { get; set; }
        public string IsSalApp { get; set; }
        public DateTime? StartDate { get; set; }
        public DateTime? EndDate { get; set; }
        public string BankAcNameUcbl { get; set; }
        public string BankAcNoUcbl { get; set; }
        public string BankAcNameSibl { get; set; }
        public string BankAcNoSibl { get; set; }
        public decimal? YearlyBonus { get; set; }
        public decimal? Gratuity { get; set; }
        public decimal? YearsOfService { get; set; }
        public string IncentiveTypeCode { get; set; }
        public decimal? Wfhallowance { get; set; }
        public decimal? SalaryDbbl { get; set; }
        public decimal? RateOfAllowancesForNightShift { get; set; }
        public decimal? NoOfNightWorked { get; set; }
        public decimal? TotalAllowancesForNightShift { get; set; }
        public decimal? OtEid { get; set; }
        public decimal? TotalAllowancesForOt { get; set; }
        public decimal? QuarterlyIncentive { get; set; }
        public decimal? NetPaymentUcbl { get; set; }
        public decimal? NetPaymentRoundUcbl { get; set; }
        public string Remarks { get; set; }
        public decimal? NoOfHolidayWorked { get; set; }
        public decimal? EidBonusDbbl { get; set; }
        public decimal? EidBonusUcb { get; set; }
        public decimal? Usd { get; set; }
    }
}