// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Data.Models
{
    public partial class HrmPayrollPfassignEntry
    {
        public decimal AutoId { get; set; }
        public string PfassignId { get; set; }
        public string EmployeeId { get; set; }
        public string PfapprovedStatus { get; set; }
        public string ApprovalRemark { get; set; }
        public DateTime Efdate { get; set; }
        public string Luser { get; set; }
        public DateTime? Ldate { get; set; }
        public string Lip { get; set; }
        public string Lmac { get; set; }
        public DateTime? ModifyDate { get; set; }
        public string CompanyCode { get; set; }
    }
}