// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Data.Models
{
    public partial class HrmPayOthersAdjustmentEntry
    {
        public decimal Tc { get; set; }
        public string OtherBenefitId { get; set; }
        public string EmployeeId { get; set; }
        public decimal? BenefitAmount { get; set; }
        public DateTime? Date { get; set; }
        public string SalaryMonth { get; set; }
        public string SalaryYear { get; set; }
        public string Remarks { get; set; }
        public string Luser { get; set; }
        public DateTime? Ldate { get; set; }
        public string Lip { get; set; }
        public string Lmac { get; set; }
        public DateTime? ModifyDate { get; set; }
        public string CompanyCode { get; set; }
        public string BenefitTypeId { get; set; }
        public decimal? PaidDays { get; set; }
    }
}