// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Data.Models
{
    public partial class HrmPayMonthlyOtentry
    {
        public decimal Tc { get; set; }
        public string MonthlyOtid { get; set; }
        public string EmployeeId { get; set; }
        public decimal? Ot { get; set; }
        public decimal? Otamount { get; set; }
        public string Month { get; set; }
        public string Year { get; set; }
        public string Remarks { get; set; }
        public string Luser { get; set; }
        public DateTime? Ldate { get; set; }
        public string Lip { get; set; }
        public string Lmac { get; set; }
        public DateTime? ModifyDate { get; set; }
        public string CompanyCode { get; set; }
    }
}