// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Data.Models
{
    public partial class HrmRosterScheduleEntry
    {
        public decimal Tc { get; set; }
        public string RosterScheduleId { get; set; }
        public string EmployeeId { get; set; }
        public DateTime Date { get; set; }
        public string ShiftCode { get; set; }
        public string Weekend { get; set; }
        public string Remark { get; set; }
        public string Luser { get; set; }
        public DateTime? Ldate { get; set; }
        public string Lip { get; set; }
        public string Lmac { get; set; }
        public DateTime? ModifyDate { get; set; }
        public string CompanyCode { get; set; }
        public string EmployeeIdSao { get; set; }
        public string ModifyBy { get; set; }
        public string ApprovalStatus { get; set; }
        public string ApprovedBy { get; set; }
        public DateTime? ApprovalDatetime { get; set; }
    }
}