// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Data.Models
{
    public partial class HrmSeparation
    {
        public decimal SeparationCode { get; set; }
        public string SeparationId { get; set; }
        public string EmployeeId { get; set; }
        public DateTime SeparationDate { get; set; }
        public string SeparationTypeId { get; set; }
        public decimal FinalPayment { get; set; }
        public string IsPaid { get; set; }
        public string Remark { get; set; }
        public string Luser { get; set; }
        public DateTime? Ldate { get; set; }
        public string Lip { get; set; }
        public string Lmac { get; set; }
        public DateTime? ModifyDate { get; set; }
        public string CompanyCode { get; set; }
        public string RefLetterNo { get; set; }
        public DateTime? RefLetterDate { get; set; }
    }
}