// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Data.Models
{
    public partial class HrmTransportExpenseEntry
    {
        public decimal AutoId { get; set; }
        public string Tedid { get; set; }
        public string Teid { get; set; }
        public DateTime? Tedate { get; set; }
        public string Luser { get; set; }
        public DateTime? Ldate { get; set; }
        public string Lip { get; set; }
        public string Lmac { get; set; }
        public DateTime? ModifyDate { get; set; }
        public string CompanyCode { get; set; }
        public string EntryUserEmployeeId { get; set; }
    }
}