// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Data.Models
{
    public partial class HrmTransportAssignEntry
    {
        public decimal AutoId { get; set; }
        public string Taid { get; set; }
        public string EmployeeId { get; set; }
        public string TransportNoId { get; set; }
        public string HelperId { get; set; }
        public string TransportTypeId { get; set; }
        public DateTime? EffectiveDate { get; set; }
        public string Active { get; set; }
        public string Luser { get; set; }
        public DateTime? Ldate { get; set; }
        public string Lip { get; set; }
        public string Lmac { get; set; }
        public DateTime? ModifyDate { get; set; }
        public string CompanyCode { get; set; }
        public string EntryUserEmployeeId { get; set; }
        public string TransportUser { get; set; }
    }
}