// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Data.Models
{
    public partial class HrmTransportExpenseDetails
    {
        public decimal AutoId { get; set; }
        public string Tedid { get; set; }
        public string Teid { get; set; }
        public string ExpenseHeadId { get; set; }
        public string Amount { get; set; }
        public string Luser { get; set; }
        public string Remarks { get; set; }
    }
}