// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace GCTL.Data.Models
{
    public partial class INV_StockReport_FilterResult
    {
        public string ProductCode { get; set; }
        public string ProductName { get; set; }
        public string Description { get; set; }
        public string BrandID { get; set; }
        public string BrandName { get; set; }
        public string CatagoryID { get; set; }
        public string CatagoryName { get; set; }
        public string ModelID { get; set; }
        public string ModelName { get; set; }
        public string SizeID { get; set; }
        public string SizeName { get; set; }
        public string UnitId { get; set; }
        public string UnitName { get; set; }
        [Column("UnitPrice", TypeName = "decimal(18,2)")]
        public decimal? UnitPrice { get; set; }
        [Column("OpeningQty", TypeName = "decimal(38,2)")]
        public decimal? OpeningQty { get; set; }
        [Column("ReceivedQty", TypeName = "decimal(38,2)")]
        public decimal ReceivedQty { get; set; }
        [Column("IssuedQty", TypeName = "decimal(38,2)")]
        public decimal IssuedQty { get; set; }
        [Column("StockQty", TypeName = "decimal(38,2)")]
        public decimal? StockQty { get; set; }
        [Column("BalanceQty", TypeName = "decimal(38,2)")]
        public decimal? BalanceQty { get; set; }
        [Column("StockValue", TypeName = "decimal(38,4)")]
        public decimal? StockValue { get; set; }
    }
}
