// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Data.Models
{
    public partial class InvDefFactory
    {
        public int FactoryCode { get; set; }
        public string FactoryId { get; set; }
        public string CustomerId { get; set; }
        public string FactoryName { get; set; }
        public string FactoryAddess { get; set; }
        public string ContactPerson { get; set; }
        public string Designation { get; set; }
        public string ContactPersonPhone { get; set; }
        public string ContactPersonEmail { get; set; }
        public DateTime? Ldate { get; set; }
        public string Luser { get; set; }
        public string Lip { get; set; }
        public string Lmac { get; set; }
        public DateTime? ModifyDate { get; set; }
        public string CompanyCode { get; set; }
    }
}