// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Data.Models
{
    public partial class InvDefItemType
    {
        public decimal AutoId { get; set; }
        public string ItemTypeId { get; set; }
        public string ItemName { get; set; }
        public string Luser { get; set; }
        public DateTime? Ldate { get; set; }
        public string Lip { get; set; }
        public string Lmac { get; set; }
        public DateTime? ModifyDate { get; set; }
        public string CompanyId { get; set; }
        public string EmployeeId { get; set; }
    }
}