// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Data.Models
{
    public partial class InvDefPackageType
    {
        public int Tc { get; set; }
        public string PackageTypeId { get; set; }
        public string PackageType { get; set; }
        public DateTime? Ldate { get; set; }
        public string Luser { get; set; }
        public string Lip { get; set; }
        public string Lmac { get; set; }
        public DateTime? ModifyDate { get; set; }
    }
}