// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Data.Models
{
    public partial class InvProductIssueInformationDetails
    {
        public decimal Tc { get; set; }
        public string Pidid { get; set; }
        public string IssueNo { get; set; }
        public string ProductCode { get; set; }
        public string BrandId { get; set; }
        public string ModelId { get; set; }
        public string SizeId { get; set; }
        public string UnitTypId { get; set; }
        public decimal? StockQty { get; set; }
        public decimal? IssueQty { get; set; }
        public string Luser { get; set; }
        public string FloorCode { get; set; }
    }
}