// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Data.Models
{
    public partial class InvSalesInvoiceInfo
    {
        public decimal AutoId { get; set; }
        public string TbreceiveNo { get; set; }
        public string InvoiceNo { get; set; }
        public DateTime? InvoiceDate { get; set; }
        public string CustomerId { get; set; }
        public string BookingType { get; set; }
        public DateTime? TbreceivedDateTime { get; set; }
        public decimal? TotalBill { get; set; }
        public decimal? Discount { get; set; }
        public decimal? VatPercentage { get; set; }
        public decimal? VatAmount { get; set; }
        public decimal? TaxPercentage { get; set; }
        public decimal? TaxAmount { get; set; }
        public string Luser { get; set; }
        public DateTime? Ldate { get; set; }
        public string Lip { get; set; }
        public string Lmac { get; set; }
        public DateTime? ModifyDate { get; set; }
        public string UserInfoEmployeeId { get; set; }
        public string CompanyCode { get; set; }
        public string Note { get; set; }
        public string Remarks { get; set; }
        public string MainCompanyCode { get; set; }
    }
}