// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Data.Models
{
    public partial class InvSalesInvoiceInfoDetails
    {
        public decimal Tc { get; set; }
        public string Sidid { get; set; }
        public string InvoiceNo { get; set; }
        public string SlNo { get; set; }
        public string ExportPickupId { get; set; }
        public string ExportDropOfId { get; set; }
        public string ImportPickupId { get; set; }
        public string ImportDropOfId { get; set; }
        public string TransportTypeId { get; set; }
        public int? NoOfTransport { get; set; }
        public DateTime? UnloadingDateTime { get; set; }
        public TimeOnly? Unloadingtime { get; set; }
        public decimal? Rate { get; set; }
        public string ShadeId { get; set; }
        public decimal? Discount { get; set; }
        public decimal? Amount { get; set; }
        public decimal? DemurrageCharge { get; set; }
        public string Luser { get; set; }
        public DateTime? Ldate { get; set; }
    }
}