// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace GCTL.Data.Models
{
    public partial class PaidReceiptsResult
    {
        public string SerialNo { get; set; }
        public int AutoId { get; set; }
        public string BillType { get; set; }
        public string BillEntryType { get; set; }
        public string BillNo { get; set; }
        public string MRNo { get; set; }
        public DateTime BillDateTime { get; set; }
        public string BillDateTimeFormatted { get; set; }
        public string BillDate { get; set; }
        public string PatientCode { get; set; }
        public string PatientName { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public string RegistrationId { get; set; }
        public string DoctorCode { get; set; }
        public string DoctorName { get; set; }
        public string ReferenceId { get; set; }
        public string ReferencePersonName { get; set; }
        [Column("Amount", TypeName = "decimal(38,2)")]
        public decimal? Amount { get; set; }
        [Column("Discount", TypeName = "decimal(18,2)")]
        public decimal? Discount { get; set; }
        [Column("Payable", TypeName = "decimal(18,2)")]
        public decimal? Payable { get; set; }
        [Column("Received", TypeName = "decimal(18,2)")]
        public decimal? Received { get; set; }
        [Column("Due", TypeName = "decimal(18,2)")]
        public decimal? Due { get; set; }
        [Column("DueReceived", TypeName = "decimal(18,2)")]
        public decimal? DueReceived { get; set; }
        [Column("Less", TypeName = "decimal(18,2)")]
        public decimal? Less { get; set; }
        public bool? IsPaid { get; set; }
        public string PaidStatus { get; set; }
        public string PatientTypeCode { get; set; }
        public string PatientTypeName { get; set; }
        public string LUser { get; set; }
        public string Remarks { get; set; }
    }
}
