// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Data.Models
{
    public partial class PaymentReceiveDetails
    {
        public decimal AutoId { get; set; }
        public string PaymentReceiveId { get; set; }
        public string InvoiceNo { get; set; }
        public decimal? Amount { get; set; }
        public string CustomerId { get; set; }
    }
}