// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Data.Models
{
    public partial class PaymentReceive
    {
        public decimal AutoId { get; set; }
        public string PaymentReceiveId { get; set; }
        public DateTime? PaymentReceiveDate { get; set; }
        public string CustomerId { get; set; }
        public string AgainstBillList { get; set; }
        public string PaymentTypeId { get; set; }
        public string ChequeNo { get; set; }
        public DateTime? ChequeDate { get; set; }
        public decimal? Amount { get; set; }
        public string DepositedAcno { get; set; }
        public string Receivedby { get; set; }
        public string Remarks { get; set; }
        public string Luser { get; set; }
        public DateTime? Ldate { get; set; }
        public string Lip { get; set; }
        public string Lmac { get; set; }
        public DateTime? ModifyDate { get; set; }
        public string CompanyCode { get; set; }
        public string MainCompanyCode { get; set; }
        public string EmployeeId { get; set; }
        public string CustomerBank { get; set; }
    }
}