// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace GCTL.Data.Models
{
    public partial class Prc_LoadGridCompanyOpeningBalanceResult
    {
        public string ComOpeningBalanceCode { get; set; }
        public string SubSusidiaryLedgerCodeNo { get; set; }
        [Column("OpeningBalance", TypeName = "decimal(18,2)")]
        public decimal? OpeningBalance { get; set; }
        public string TrType { get; set; }
        public string Main_CompanyCode { get; set; }
    }
}
