// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace GCTL.Data.Models
{
    public partial class prc_GetTestAmountBySubCatagoryResult
    {
        [Column("DiscountPercent", TypeName = "decimal(18,2)")]
        public decimal? DiscountPercent { get; set; }
        [Column("DiscountAmount", TypeName = "decimal(18,2)")]
        public decimal? DiscountAmount { get; set; }
        [Column("Amount", TypeName = "decimal(18,2)")]
        public decimal? Amount { get; set; }
    }
}
