// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace GCTL.Data.Models
{
    public partial class prc_VSGridFilerResult
    {
        public string TBReceiveNO { get; set; }
        public string TBReceivedDateTime { get; set; }
        public string BookingType { get; set; }
        public string CustomerName { get; set; }
        public string Remarks { get; set; }
        public string IsVendorAdded { get; set; }
        public string className { get; set; }
        public string totalPrice { get; set; }
    }
}
