// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace GCTL.Data.Models
{
    public partial class Prc_Frm_TempAccountDetailsResult
    {
        public string AccCode { get; set; }
        public string AccountHead { get; set; }
        public string TrType { get; set; }
        public string Description { get; set; }
        [Column("DebitAmount", TypeName = "decimal(18,2)")]
        public decimal? DebitAmount { get; set; }
        [Column("CreditAmount", TypeName = "decimal(18,2)")]
        public decimal? CreditAmount { get; set; }
        public string ChequeNo { get; set; }
        public string ChequeDate { get; set; }
    }
}
