// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace GCTL.Data.Models
{
    public partial class Prc_Load_ThirdAcountHeadResult
    {
        public string GeneralLedgerCodeNo { get; set; }
        public string GeneralLedgerName { get; set; }
    }
}
