// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace GCTL.Data.Models
{
    public partial class Prc_LoadGrid_Acc_SubSubsidiaryLedgerResult
    {
        public string SubSusidiaryLedgerCodeNo { get; set; }
        public string SubSubsidiaryLedgerName { get; set; }
        public string SubsidiaryLedgerName { get; set; }
        public string GeneralLedgerName { get; set; }
        [Column("OpeningBalance", TypeName = "decimal(18,2)")]
        public decimal? OpeningBalance { get; set; }
    }
}
