// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace GCTL.Data.Models
{
    public partial class Proc_getVendorListResult
    {
        public string TBReceiveNO { get; set; }
        public string VendorName { get; set; }
        [Column("VendorRate", TypeName = "decimal(18,2)")]
        public decimal? VendorRate { get; set; }
        [Column("NoOfTransport", TypeName = "decimal(7,2)")]
        public decimal? NoOfTransport { get; set; }
        public string VendorID { get; set; }
        public string SlNo { get; set; }
        public string TBRSlNo { get; set; }
        [Column("Amount", TypeName = "decimal(18,2)")]
        public decimal? Amount { get; set; }
        public string TransportType { get; set; }
    }
}
