// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace GCTL.Data.Models
{
    public partial class proc_ExpenseReportResult
    {
        public string ExpenseCode { get; set; }
        public string ExpenseDate { get; set; }
        public string ExpenseHead { get; set; }
        [Column("Amount", TypeName = "decimal(18,2)")]
        public decimal Amount { get; set; }
        public string PaymentModeName { get; set; }
        public string Remarks { get; set; }
        public string SearchFromDate { get; set; }
        public string SearchToDate { get; set; }
    }
}
