// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace GCTL.Data.Models
{
    public partial class PROCPrintingAndStationeryReportResult
    {
        public string PurchaseOrderReceiveDetailsID { get; set; }
        public string ProductCode { get; set; }
        public string ProductName { get; set; }
        public string Description { get; set; }
        public string CatagoryID { get; set; }
        public string CatagoryName { get; set; }
        public string BrandID { get; set; }
        public string BrandName { get; set; }
        public string ModelID { get; set; }
        public string ModelName { get; set; }
        public string SizeID { get; set; }
        public string SizeName { get; set; }
        public string WarrantyPeriod { get; set; }
        public string PeriodName { get; set; }
        public DateTime? ReceiveDate { get; set; }
        [Column("ReqQty", TypeName = "decimal(18,2)")]
        public decimal? ReqQty { get; set; }
        public string UnitTypeName { get; set; }
        [Column("PurchaseCost", TypeName = "decimal(18,2)")]
        public decimal? PurchaseCost { get; set; }
        [Column("TotalPrice", TypeName = "decimal(18,2)")]
        public decimal? TotalPrice { get; set; }
    }
}
