// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace GCTL.Data.Models
{
    public partial class ProcProbationPeriodExtensionEntryResult
    {
        public string EmployeeID { get; set; }
        public string FullName { get; set; }
        public string CompanyCode { get; set; }
        public string CompanyName { get; set; }
        public string DesignationName { get; set; }
        public string DepartmentName { get; set; }
        public DateTime? JoiningDate { get; set; }
        [Column("GrossSalary", TypeName = "decimal(18,2)")]
        public decimal GrossSalary { get; set; }
        public DateTime? ContractEndDate { get; set; }
        public string ProbationPeriod { get; set; }
        public string DurationSinceJoining { get; set; }
    }
}
