// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace GCTL.Data.Models
{
    public partial class Proc_getOrderListResult
    {
        public string TBReceiveNO { get; set; }
        public string BookingType { get; set; }
        public string CustomerID { get; set; }
        public string CustomerName { get; set; }
        public string CompanyName { get; set; }
        public string CompanyCode { get; set; }
        public int? TotalNoOFTransport { get; set; }
        public string SlNo { get; set; }
        public string ExportPickupID { get; set; }
        public string ExportDropOfID { get; set; }
        public string LocalPickupID { get; set; }
        public string LocalDropOfID { get; set; }
        public string ImportPickupID { get; set; }
        public string ImportDropOfID { get; set; }
        public string ShadeID { get; set; }
        public int? NoOfTransport { get; set; }
        public string LoadingDateTime { get; set; }
        public string ExportPickupName { get; set; }
        public string ExportDroplocationName { get; set; }
        public string ImportPickupName { get; set; }
        public string ImportDroplocationName { get; set; }
        public string LocalPickupName { get; set; }
        public string LocalDroplocationName { get; set; }
        public string ShadeName { get; set; }
        [Column("Amount", TypeName = "decimal(18,2)")]
        public decimal? Amount { get; set; }
        public string TransportTypeName { get; set; }
        public string TransportTypeID { get; set; }
        [Column("Rate", TypeName = "decimal(18,2)")]
        public decimal Rate { get; set; }
        [Column("VendorRate", TypeName = "decimal(18,2)")]
        public decimal VendorRate { get; set; }
        [Column("VendorAmount", TypeName = "decimal(18,2)")]
        public decimal? VendorAmount { get; set; }
        [Column("ModifiedRate", TypeName = "decimal(18,2)")]
        public decimal ModifiedRate { get; set; }
        [Column("ModifiedAmount", TypeName = "decimal(18,2)")]
        public decimal? ModifiedAmount { get; set; }
    }
}
