// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace GCTL.Data.Models
{
    public partial class Proc_getCustomerInvoiceDueListResult
    {
        public string InvoiceNo { get; set; }
        public string InvoiceDate { get; set; }
        [Column("TotalBill", TypeName = "decimal(38,2)")]
        public decimal? TotalBill { get; set; }
        [Column("Due", TypeName = "decimal(38,2)")]
        public decimal? Due { get; set; }
    }
}
