// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace GCTL.Data.Models
{
    public partial class Proc_getOrderListHeaderResult
    {
        public string TBReceiveNO { get; set; }
        public string BookingType { get; set; }
        public string CustomerID { get; set; }
        public string CustomerName { get; set; }
        public string CompanyName { get; set; }
        public string CompanyCode { get; set; }
        public int? TotalNoOFTransport { get; set; }
    }
}
