// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace GCTL.Data.Models
{
    public partial class proc_GetPatientListForLabTestResultResult
    {
        public string LabTestNo { get; set; }
        public string Mrno { get; set; }
        public string MrdateTime { get; set; }
        public string PatientCode { get; set; }
        public string PatientName { get; set; }
        public string FullAge { get; set; }
        public int? Age { get; set; }
        public string Sex { get; set; }
        public string RegistrationId { get; set; }
        public string DoctorName { get; set; }
        public string ReferencePerson { get; set; }
    }
}
