// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace GCTL.Data.Models
{
    public partial class QualificationReportSPResult
    {
        public string EmployeeID { get; set; }
        public string EmployeeName { get; set; }
        public string DesignationName { get; set; }
        public string DepartmentName { get; set; }
        public string CourseCode { get; set; }
        public string CourseName { get; set; }
        public string JoiningDate { get; set; }
        public string NationalIDNO { get; set; }
        public string InstituteName { get; set; }
        public string InstituteAddress { get; set; }
        public string ResultDivision { get; set; }
        public string YearofPasssing { get; set; }
        public string Dueration { get; set; }
        public string CompanyName { get; set; }
        public string Address1 { get; set; }
    }
}
