// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace GCTL.Data.Models
{
    public partial class ReferenceCommissionSummaryResult
    {
        public string CommissionReceiver { get; set; }
        public string CommissionReceiverId { get; set; }
        public string CommissionReceiverName { get; set; }
        [Column("TotalPayableCommission", TypeName = "decimal(38,6)")]
        public decimal? TotalPayableCommission { get; set; }
        [Column("TotalDue", TypeName = "decimal(38,6)")]
        public decimal? TotalDue { get; set; }
        [Column("LastPayment", TypeName = "decimal(18,2)")]
        public decimal? LastPayment { get; set; }
        public DateTime? LastPaymentDate { get; set; }
    }
}
