// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace GCTL.Data.Models
{
    public partial class ReferenceCommissionReportResult
    {
        public string CommissionReceiver { get; set; }
        public string CommissionReceiverId { get; set; }
        public string CommissionReceiverName { get; set; }
        public string TestCategoryName { get; set; }
        public string TestChargeName { get; set; }
        [Column("Amount", TypeName = "decimal(18,2)")]
        public decimal? Amount { get; set; }
        [Column("NetAmount", TypeName = "decimal(18,2)")]
        public decimal? NetAmount { get; set; }
        [Column("CommissionPercent", TypeName = "decimal(18,2)")]
        public decimal? CommissionPercent { get; set; }
        [Column("CommissionAmount", TypeName = "decimal(18,2)")]
        public decimal? CommissionAmount { get; set; }
        [Column("PayableAmount", TypeName = "decimal(18,2)")]
        public decimal? PayableAmount { get; set; }
    }
}
