// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Data.Models
{
    public partial class RmgDefSupplier
    {
        public decimal Tc { get; set; }
        public string SupplierId { get; set; }
        public string SupplierName { get; set; }
        public string SupplierTitle { get; set; }
        public string SupplierCode { get; set; }
        public string SupplierCategoryId { get; set; }
        public string SupplierTypeId { get; set; }
        public string Address { get; set; }
        public string LocalOfficeAddress { get; set; }
        public string CompanyId { get; set; }
        public string SupplierOriginId { get; set; }
        public string CountryId { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string ZipCode { get; set; }
        public string Phone { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public string Url { get; set; }
        public string SupplierTin { get; set; }
        public string SupplierBankId { get; set; }
        public string SupplierBankBranchId { get; set; }
        public string IalbankId { get; set; }
        public string IalbankBranchId { get; set; }
        public string ContatPerson1 { get; set; }
        public string DesignationId { get; set; }
        public string Phone1 { get; set; }
        public string Email1 { get; set; }
        public string ContatPerson2 { get; set; }
        public string DesignationId2 { get; set; }
        public string Phone2 { get; set; }
        public string Email2 { get; set; }
        public string ContatPerson3 { get; set; }
        public string DesignationId3 { get; set; }
        public string Phone3 { get; set; }
        public string Email3 { get; set; }
        public decimal? OpeningBalance { get; set; }
        public string Optype { get; set; }
        public string SalesPersonId { get; set; }
        public string Remarks { get; set; }
        public string Active { get; set; }
        public string Luser { get; set; }
        public DateTime? Ldate { get; set; }
        public string Lip { get; set; }
        public string Lmac { get; set; }
        public DateTime? ModifyDate { get; set; }
        public string ExportLicenceNo { get; set; }
        public string BranchAddress { get; set; }
        public string AccountNo { get; set; }
        public string SwiftCode { get; set; }
        public string Bin { get; set; }
        public string VatregNo { get; set; }
    }
}