// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Data.Models
{
    public partial class RmgProdTempColorSizeBreakup
    {
        public decimal Tc { get; set; }
        public string BreakNo { get; set; }
        public string DetailOrderId { get; set; }
        public string ColorId { get; set; }
        public string SizeId { get; set; }
        public int? Quantity { get; set; }
        public string UnitTypeId { get; set; }
        public string Remarks { get; set; }
        public string Luser { get; set; }
        public DateTime? Ldate { get; set; }
        public string Lip { get; set; }
        public string Lmac { get; set; }
        public DateTime? ModifyDate { get; set; }
        public string CompanyCode { get; set; }
        public string IntegraJobno { get; set; }
    }
}