// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Data.Models
{
    public partial class RmgPurchaseOrderReceive
    {
        public decimal Tc { get; set; }
        public string MainCompanyCode { get; set; }
        public string PurchaseReceiveNo { get; set; }
        public DateTime? ReceiveDate { get; set; }
        public string DepartmentCode { get; set; }
        public string SupplierId { get; set; }
        public string InvoiceNo { get; set; }
        public DateTime? InvoiceDate { get; set; }
        public decimal? InvoiceValue { get; set; }
        public string ChallanNo { get; set; }
        public DateTime? ChallanDate { get; set; }
        public string EmployeeIdReceiveBy { get; set; }
        public string Remarks { get; set; }
        public decimal? TotalAmount { get; set; }
        public string Luser { get; set; }
        public DateTime? Ldate { get; set; }
        public string Lip { get; set; }
        public string Lmac { get; set; }
        public DateTime? ModifyDate { get; set; }
        public string UserInfoEmployeeId { get; set; }
        public string CompanyCode { get; set; }
    }
}