// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Data.Models
{
    public partial class RmgProdDefPackage
    {
        public int Tc { get; set; }
        public string PackageId { get; set; }
        public string PackageName { get; set; }
        public string Type { get; set; }
        public string Volume { get; set; }
        public int? MaxCapacity { get; set; }
        public string UnitTypId { get; set; }
        public string Remarks { get; set; }
        public string Luser { get; set; }
        public DateTime? Ldate { get; set; }
        public string Lip { get; set; }
        public string Lmac { get; set; }
        public DateTime? ModifyDate { get; set; }
    }
}