// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Data.Models
{
    public partial class RmgProdDefSize
    {
        public decimal Tc { get; set; }
        public string SizeId { get; set; }
        public string Size { get; set; }
        public string Detail { get; set; }
        public string Luser { get; set; }
        public DateTime? Ldate { get; set; }
        public string Lip { get; set; }
        public string Lmac { get; set; }
        public DateTime? ModifyDate { get; set; }
        public int? Slno { get; set; }
    }
}