// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Data.Models
{
    public partial class RmgPurchaseOrderReceiveDetails
    {
        public decimal Tc { get; set; }
        public string PurchaseOrderReceiveDetailsId { get; set; }
        public string PurchaseReceiveNo { get; set; }
        public string ProductCode { get; set; }
        public string Description { get; set; }
        public string BrandId { get; set; }
        public string ModelId { get; set; }
        public string SizeId { get; set; }
        public string WarrantyPeriod { get; set; }
        public string WarrentyTypeId { get; set; }
        public decimal? ReqQty { get; set; }
        public string UnitTypId { get; set; }
        public decimal? UnitPrice { get; set; }
        public decimal? TotalPrice { get; set; }
        public string Luser { get; set; }
        public int? Slno { get; set; }
    }
}