// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace GCTL.Data.Models
{
    public partial class Rpt_Proc_InvoiceReportResult
    {
        public string CompanyName { get; set; }
        public string Address1 { get; set; }
        public string PhoneFax { get; set; }
        public string Email { get; set; }
        public string InvoiceNo { get; set; }
        public string InvoiceDate { get; set; }
        public string TBReceiveNO { get; set; }
        public string CustomerName { get; set; }
        public string CustomerAddress { get; set; }
        public string Phone { get; set; }
        [Column("TotalBill", TypeName = "decimal(18,2)")]
        public decimal? TotalBill { get; set; }
        public string BookingType { get; set; }
        public string TransportType { get; set; }
        public int? NoOfTransport { get; set; }
        [Column("Rate", TypeName = "decimal(18,2)")]
        public decimal? Rate { get; set; }
        [Column("Amount", TypeName = "decimal(18,2)")]
        public decimal? Amount { get; set; }
        [Column("DemurrageCharge", TypeName = "decimal(18,2)")]
        public decimal DemurrageCharge { get; set; }
        [Column("SubTotal", TypeName = "decimal(19,2)")]
        public decimal? SubTotal { get; set; }
        public string Remarks { get; set; }
    }
}
