// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace GCTL.Data.Models
{
    public partial class Rpt_proc_BSNonCurrentAssetResult
    {
        public string SubControlLedgerName { get; set; }
        public string GeneralLedgerName { get; set; }
        [Column("Amount", TypeName = "decimal(38,2)")]
        public decimal? Amount { get; set; }
        [Column("TFS", TypeName = "decimal(38,2)")]
        public decimal? TFS { get; set; }
    }
}
