// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace GCTL.Data.Models
{
    public partial class Rpt_PatientInfoResult
    {
        public string RegistrationId { get; set; }
        public string RegistrationDate { get; set; }
        public string PatientTypeCode { get; set; }
        public string PatientTypeName { get; set; }
        public string PatientCategoryCode { get; set; }
        public string PatientCategoryName { get; set; }
        public string AdmissionTypeId { get; set; }
        public string AdmissionTypeName { get; set; }
        public string PatientCode { get; set; }
        public string PatientName { get; set; }
        public string Sex { get; set; }
        public string Age { get; set; }
        public string FatherHusbandName { get; set; }
        public string PresentAddress { get; set; }
        public string PermanentAddress { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string NationalIdNo { get; set; }
        public string GuardianName { get; set; }
        public string GuardianPhone { get; set; }
        public string RelationCode { get; set; }
        public string Relation { get; set; }
        public string RefDoctorName { get; set; }
        public string RefDoctorPhone { get; set; }
        public string AdmissionDate { get; set; }
        public string PrimaryCare_DoctorName { get; set; }
        public string Disease { get; set; }
        public string RoomDetails { get; set; }
        public string DepartmentName { get; set; }
        public string DoctorName { get; set; }
        public string ExpectedLengthStay { get; set; }
        [Column("AdvancePayment", TypeName = "decimal(18,2)")]
        public decimal? AdvancePayment { get; set; }
        public string PaymentModeName { get; set; }
        public string InWords { get; set; }
    }
}
