// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace GCTL.Data.Models
{
    public partial class Rpt_Proc_OutPatientPrescriptionReportResult
    {
        public long? Sl { get; set; }
        public string PrescriptionId { get; set; }
        public DateOnly? PrescriptionDate { get; set; }
        public string PatientCode { get; set; }
        public string PatientName { get; set; }
        public string Age { get; set; }
        public string Sex { get; set; }
        public string DoctorName { get; set; }
        public string ReferencePersonName { get; set; }
        public string PType { get; set; }
        [Column("TotalFee", TypeName = "decimal(19,2)")]
        public decimal? TotalFee { get; set; }
        [Column("Discount", TypeName = "decimal(18,2)")]
        public decimal Discount { get; set; }
        [Column("AfterDiscountAmount", TypeName = "decimal(18,2)")]
        public decimal? AfterDiscountAmount { get; set; }
        public string FormatPrescriptionDate { get; set; }
    }
}
