// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace GCTL.Data.Models
{
    public partial class Rpt_proc_PLTotalInDirectExpenseResult
    {
        public string aslName { get; set; }
        public string asslName { get; set; }
        [Column("Amount", TypeName = "decimal(38,2)")]
        public decimal? Amount { get; set; }
        [Column("TIDE", TypeName = "decimal(38,2)")]
        public decimal? TIDE { get; set; }
    }
}
