// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Data.Models
{
    public partial class SalesDefVehicleType
    {
        public int Tc { get; set; }
        public string VehicleTypeId { get; set; }
        public string VehicleType { get; set; }
        public string ShortName { get; set; }
        public string Luser { get; set; }
        public DateTime? Ldate { get; set; }
        public string Lip { get; set; }
        public string Lmac { get; set; }
        public DateTime? ModifyDate { get; set; }
        public decimal? StorageSize { get; set; }
        public string StorageUnitId { get; set; }
        public decimal? WeightLoadCapacity { get; set; }
        public string CapacityUnitId { get; set; }
    }
}