// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Data.Models
{
    public partial class SalesDefBankBranchInfo
    {
        public int AutoId { get; set; }
        public string BankBranchId { get; set; }
        public string BankBranchName { get; set; }
        public string ShortName { get; set; }
        public string BankId { get; set; }
        public string Swiftcode { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public DateTime? Ldate { get; set; }
        public string Luser { get; set; }
        public string Lip { get; set; }
        public string Lmac { get; set; }
        public DateTime? ModifyDate { get; set; }
    }
}