// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Data.Models
{
    public partial class SalesDefVehicle
    {
        public int Tc { get; set; }
        public string VehicleId { get; set; }
        public string VehicleNo { get; set; }
        public string VehicleTypeId { get; set; }
        public string Remarks { get; set; }
        public string Luser { get; set; }
        public DateTime? Ldate { get; set; }
        public string Lip { get; set; }
        public string Lmac { get; set; }
        public DateTime? ModifyDate { get; set; }
        public string FactoryId { get; set; }
        public string CompanyCode { get; set; }
        public string PortNameId { get; set; }
        public string EmployeeId { get; set; }
        public string Phone { get; set; }
        public string VendorId { get; set; }
        public decimal? StorageSize { get; set; }
        public string StorageUnitId { get; set; }
        public decimal? WeightLoadCapacity { get; set; }
        public decimal? TransportCapacity { get; set; }
        public string CapacityUnitId { get; set; }
        public decimal? TransportLength { get; set; }
        public decimal? TransportWidth { get; set; }
        public decimal? TransportHeight { get; set; }
        public string UnitTypIdCbm { get; set; }
        public decimal? TotalVolume { get; set; }
    }
}