// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Data.Models
{
    public partial class SalesCustomer
    {
        public decimal AutoId { get; set; }
        public string CustomerId { get; set; }
        public string CustomerName { get; set; }
        public string CustomerCompany { get; set; }
        public string CustomerAddress { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public decimal? OpeningBalance { get; set; }
        public string ContatPerson1 { get; set; }
        public string Designation1 { get; set; }
        public string Phone1 { get; set; }
        public string ContatPerson2 { get; set; }
        public string Designation2 { get; set; }
        public string Phone2 { get; set; }
        public string ContatPerson3 { get; set; }
        public string Designation3 { get; set; }
        public string Phone3 { get; set; }
        public decimal? CreditLimit { get; set; }
        public string Luser { get; set; }
        public DateTime? Ldate { get; set; }
        public string Lip { get; set; }
        public string Lmac { get; set; }
        public string Fax { get; set; }
        public string Url { get; set; }
        public string Email1 { get; set; }
        public string Email2 { get; set; }
        public string Email3 { get; set; }
        public string CustomerType { get; set; }
        public string Category { get; set; }
        public string SalesPersonId { get; set; }
        public string Bin { get; set; }
        public string CustomerSectorId { get; set; }
        public string CountryId { get; set; }
        public string Vat { get; set; }
        public string Tin { get; set; }
        public DateTime? OpeningDate { get; set; }
        public string DistrictsId { get; set; }
        public string Place { get; set; }
        public decimal? DamageCost { get; set; }
    }
}