// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Data.Models
{
    public partial class SalesDefDeportInfo
    {
        public decimal AutoId { get; set; }
        public string DeportId { get; set; }
        public string DeportName { get; set; }
        public string Address { get; set; }
        public string CountryId { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string ZipCode { get; set; }
        public string Cpid { get; set; }
        public string Remarks { get; set; }
        public string Luser { get; set; }
        public DateTime? Ldate { get; set; }
        public string Lip { get; set; }
        public string Lmac { get; set; }
        public DateTime? ModifyDate { get; set; }
        public string UserInfoEmployeeId { get; set; }
        public string CompanyCode { get; set; }
    }
}