// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace GCTL.Data.Models
{
    public partial class SalesReportForUserResult
    {
        public string SerialNo { get; set; }
        public string BillType { get; set; }
        public string BillEntryType { get; set; }
        public string BillNo { get; set; }
        public string MRNo { get; set; }
        public DateTime BillDateTime { get; set; }
        public string BillDate { get; set; }
        public string PatientCode { get; set; }
        public string PatientName { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public string RegistrationId { get; set; }
        public string DoctorCode { get; set; }
        public string DoctorName { get; set; }
        public string ReferenceId { get; set; }
        public string ReferencePersonName { get; set; }
        [Column("Amount", TypeName = "decimal(38,2)")]
        public decimal? Amount { get; set; }
        [Column("Discount", TypeName = "decimal(18,2)")]
        public decimal? Discount { get; set; }
        [Column("NetSales", TypeName = "decimal(18,2)")]
        public decimal? NetSales { get; set; }
        public string PatientTypeCode { get; set; }
        public string PatientTypeName { get; set; }
    }
}
