// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Data.Models
{
    public partial class SalesDefDriverInformation
    {
        public decimal AutoId { get; set; }
        public string DriverId { get; set; }
        public string DriverName { get; set; }
        public string Address { get; set; }
        public string CompanyId { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string Nid { get; set; }
        public DateTime? Dob { get; set; }
        public string LicenseNo { get; set; }
        public DateTime? IssueDate { get; set; }
        public DateTime? ExpiryDate { get; set; }
        public string LicenseCategory { get; set; }
        public string Luser { get; set; }
        public DateTime? Ldate { get; set; }
        public string Lip { get; set; }
        public string Lmac { get; set; }
        public DateTime? ModifyDate { get; set; }
        public string UserInfoEmployeeId { get; set; }
        public string CompanyCode { get; set; }
    }
}