// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace GCTL.Data.Models
{
    public partial class sp_gc_department_list_by_accessResult
    {
        public string Code { get; set; }
        public string Name { get; set; }
        public bool? More { get; set; }
    }
}
