// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace GCTL.Data.Models
{
    public partial class SP_HRM_AdvancePayReportResult
    {
        public string CompanyName { get; set; }
        public string CompanyCode { get; set; }
        public string BranchCode { get; set; }
        public string BranchName { get; set; }
        public string DepartmentCode { get; set; }
        public string DepartmentName { get; set; }
        public string DesignationCode { get; set; }
        public string DesignationName { get; set; }
        public string EmployeeID { get; set; }
        public string FullName { get; set; }
        public string PayHeadNameId { get; set; }
        public string PayHeadName { get; set; }
        public byte? MonthId { get; set; }
        public string MonthName { get; set; }
        public string SalaryYear { get; set; }
        [Column("AdvanceAmount", TypeName = "decimal(10,2)")]
        public decimal AdvanceAmount { get; set; }
        [Column("MonthlyDeduction", TypeName = "decimal(10,2)")]
        public decimal MonthlyDeduction { get; set; }
        public string Remarks { get; set; }
        public int? TotalInThisDepartment { get; set; }
    }
}
