// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Data.Models
{
    public partial class TbmTransportBookingReceived
    {
        public TbmTransportBookingReceived()
        {
            TbmTransportBookingReceivedDetails = new HashSet<TbmTransportBookingReceivedDetails>();
        }

        public decimal Tc { get; set; }
        public string TbreceiveNo { get; set; }
        public string CustomerId { get; set; }
        public string BookingType { get; set; }
        public DateTime? TbreceivedDateTime { get; set; }
        public string Luser { get; set; }
        public DateTime? Ldate { get; set; }
        public string Lip { get; set; }
        public string Lmac { get; set; }
        public string CompanyCode { get; set; }
        public string LoginEmployeeId { get; set; }
        public string Remarks { get; set; }
        public string OrderStatus { get; set; }
        public string IsMailSent { get; set; }
        public string IscustomerApprove { get; set; }
        public DateTime? ApprovalDateTime { get; set; }
        public string IsVendorAdded { get; set; }
        public string IsTransportInfoAdded { get; set; }
        public DateTime? VendorAddedDateTime { get; set; }
        public DateTime? TranspotInfoAddedDateTime { get; set; }
        public string IsTrackingComplete { get; set; }
        public string IsBillSubmited { get; set; }

        public virtual ICollection<TbmTransportBookingReceivedDetails> TbmTransportBookingReceivedDetails { get; set; }
    }
}