// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Data.Models
{
    public partial class TbmTransportListDetails
    {
        public decimal Tltc { get; set; }
        public string TbreceiveNo { get; set; }
        public string SlNo { get; set; }
        public string VenSlNo { get; set; }
        public string VendorId { get; set; }
        public string DriverName { get; set; }
        public string DriverPhone { get; set; }
        public string VehicleNo { get; set; }
        public DateTime? LoadingPointArrivalTime { get; set; }
        public DateTime? LoadingCompleteTime { get; set; }
        public DateTime? UnloadingPointArrivalTime { get; set; }
        public DateTime? UnloadingCompleteTime { get; set; }
        public decimal? DemurrageCharge { get; set; }
        public int? DayCount { get; set; }
        public decimal? DemurrageUnitChange { get; set; }
        public string TbrslNo { get; set; }
        public string VncityName { get; set; }
        public string VnclassName { get; set; }
        public string VnfirstNumber { get; set; }
        public string VnsecondNumber { get; set; }
    }
}