// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Data.Models
{
    public partial class TbmTransportBookingReceivedDetails
    {
        public decimal Tc { get; set; }
        public string TbreceiveNo { get; set; }
        public string SlNo { get; set; }
        public string ExportPickupId { get; set; }
        public string ExportDropOfId { get; set; }
        public string ImportPickupId { get; set; }
        public string ImportDropOfId { get; set; }
        public string TransportTypeId { get; set; }
        public int? NoOfTransport { get; set; }
        public decimal? Rate { get; set; }
        public string VendorId { get; set; }
        public string ShadeId { get; set; }
        public decimal? VendorRate { get; set; }
        public decimal? CustomerModifiedRate { get; set; }
        public DateTime? LoadingDateTime { get; set; }
        public string LocalPickupId { get; set; }
        public string LocalDropOfId { get; set; }

        public virtual TbmTransportBookingReceived TbreceiveNoNavigation { get; set; }
    }
}