// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Data.Models
{
    public partial class TbmVendorAssignDetails
    {
        public decimal Vltc { get; set; }
        public string TbreceiveNo { get; set; }
        public string SlNo { get; set; }
        public string TbrslNo { get; set; }
        public string VendorId { get; set; }
        public decimal? VendorRate { get; set; }
        public decimal? Amount { get; set; }
        public int? NoOfTransport { get; set; }
        public int? NoOfTransportBill { get; set; }
        public decimal? VendorBillRate { get; set; }
        public decimal? BillAmount { get; set; }
    }
}