// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Data.Models
{
    public partial class TransportItemDetails
    {
        public int Id { get; set; }
        public string TbreceiveNo { get; set; }
        public string VehicleNo { get; set; }
        public string ItemDescription { get; set; }
        public int? Quantity { get; set; }
        public string UnitTypeId { get; set; }
        public decimal? Weight { get; set; }
        public string WeightUnitTypeId { get; set; }
        public string Cbm { get; set; }
    }
}