// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace GCTL.Data.Models
{
    public partial class usp_GetPayrollMasterFile_GeneralResult
    {
        [Column("SL.")]
        public long? SL { get; set; }
        [Column("ID NO.")]
        public string IDNO { get; set; }
        [Column("Pay ID")]
        public string PayID { get; set; }
        [Column("DP User ID")]
        public string DPUserID { get; set; }
        [Column("DBBL Employees Name")]
        public string DBBLEmployeesName { get; set; }
        [Column("UCBL Employees Name")]
        public string UCBLEmployeesName { get; set; }
        public string Status { get; set; }
        public string DEPARTMENT { get; set; }
        public string DESIGNATION { get; set; }
        public string DOH { get; set; }
        public string DOT { get; set; }
        [Column("Duration", TypeName = "decimal(10,2)")]
        public decimal? Duration { get; set; }
        public string DBBL { get; set; }
        public string UCBL { get; set; }
        [Column("Salary", TypeName = "decimal(18,2)")]
        public decimal? Salary { get; set; }
        [Column("Yearly Bonus Eligibility")]
        public string YearlyBonusEligibility { get; set; }
        [Column("Gratuity Eligibility")]
        public string GratuityEligibility { get; set; }
        [Column("Eid Bonus Eligibility", TypeName = "decimal(10,2)")]
        public decimal? EidBonusEligibility { get; set; }
        [Column("PF Eligiblity", TypeName = "decimal(10,2)")]
        public decimal? PFEligiblity { get; set; }
        public string Gender { get; set; }
        [Column("Cell Phone")]
        public string CellPhone { get; set; }
        [Column("Special Notes")]
        public string SpecialNotes { get; set; }
        [Column("End of Probation")]
        public string EndofProbation { get; set; }
        [Column("Mode of Payment")]
        public string ModeofPayment { get; set; }
        [Column("Employment Nature")]
        public string EmploymentNature { get; set; }
    }
}
