// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace GCTL.Data.Models
{
    public partial class USP_TransportExpenseReportResult
    {
        public string VehicleID { get; set; }
        public string VehicleNo { get; set; }
        public string VehicleTypeID { get; set; }
        public string VehicleType { get; set; }
        [Column("TransportCapacity", TypeName = "decimal(18,2)")]
        public decimal? TransportCapacity { get; set; }
        public string EmployeeID { get; set; }
        public string FullName { get; set; }
        public string HelperId { get; set; }
        [Column("Helper Name")]
        public string HelperName { get; set; }
        [Column("CNG /Gas Bill", TypeName = "decimal(38,2)")]
        public decimal CNGGasBill { get; set; }
        [Column("R/M Bill", TypeName = "decimal(38,2)")]
        public decimal RMBill { get; set; }
        [Column("Fuel/Octane bill", TypeName = "decimal(38,2)")]
        public decimal FuelOctanebill { get; set; }
        [Column("Police Donation", TypeName = "decimal(38,2)")]
        public decimal PoliceDonation { get; set; }
        [Column("Toll/others Bill", TypeName = "decimal(38,2)")]
        public decimal TollothersBill { get; set; }
        [Column("TAX ,Fitness And Rute Permit", TypeName = "decimal(38,2)")]
        public decimal TAXFitnessAndRutePermit { get; set; }
        [Column("Salary(Driver,Helper)", TypeName = "decimal(38,2)")]
        public decimal SalaryDriverHelper { get; set; }
        [Column("Mechanic Salary", TypeName = "decimal(38,2)")]
        public decimal MechanicSalary { get; set; }
        [Column("Monthly Police Donation", TypeName = "decimal(38,2)")]
        public decimal MonthlyPoliceDonation { get; set; }
        [Column("Monthly Eng.Oil Purchase", TypeName = "decimal(38,2)")]
        public decimal MonthlyEngOilPurchase { get; set; }
        [Column("Akesh Technology", TypeName = "decimal(38,2)")]
        public decimal AkeshTechnology { get; set; }
        [Column("Garage Rent", TypeName = "decimal(38,2)")]
        public decimal GarageRent { get; set; }
        [Column("TotalExpense", TypeName = "decimal(38,2)")]
        public decimal? TotalExpense { get; set; }
    }
}
