// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace GCTL.Data.Models
{
    public partial class usp_GetAttendanceMovementResult
    {
        public int TotalEmployees { get; set; }
        public int PresentCount { get; set; }
        public int LateCount { get; set; }
        public int OnLeaveCount { get; set; }
        public int AbsentCount { get; set; }
        [Column("PresentPct", TypeName = "decimal(1,1)")]
        public decimal PresentPct { get; set; }
        [Column("LatePct", TypeName = "decimal(1,1)")]
        public decimal LatePct { get; set; }
        [Column("OnLeavePct", TypeName = "decimal(1,1)")]
        public decimal OnLeavePct { get; set; }
        [Column("AbsentPct", TypeName = "decimal(1,1)")]
        public decimal AbsentPct { get; set; }
        public int? DataDate { get; set; }
    }
}
