// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace GCTL.Data.Models
{
    public partial class WorkingExperienceReportSPResult
    {
        public string EmployeeID { get; set; }
        public string EmployeeName { get; set; }
        public string DepartmentName { get; set; }
        public string DesignationName { get; set; }
        public string JoiningDate { get; set; }
        public string NationalIDNO { get; set; }
        public string CompanyName { get; set; }
        public string Address1 { get; set; }
        public string DesignationNameExp { get; set; }
        public string Responsibilities { get; set; }
        [Column("Salary", TypeName = "decimal(18,2)")]
        public decimal Salary { get; set; }
        public string Remarks { get; set; }
        public string BusinessType { get; set; }
        public string FromDate { get; set; }
        public string ToDate { get; set; }
    }
}
