<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Content Remove="C:\Users\siamm\.nuget\packages\tono.excel\1.0.7\contentFiles\any\netstandard2.0\TonoCoreIcon.png" />
    <Content Remove="C:\Users\siamm\.nuget\packages\tono.excel\1.0.7\contentFiles\any\netstandard2.0\TonoExcel.snk" />
    <Content Remove="C:\Users\siamm\.nuget\packages\tono.excel\1.0.7\contentFiles\any\netstandard2.0\TonoExcelIcon.png" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Dapper" Version="2.0.123" />
    <PackageReference Include="EfCore.SchemaCompare" Version="6.0.0" />
    <PackageReference Include="ErikEJ.EntityFrameworkCore.SqlServer.DateOnlyTimeOnly" Version="6.0.11" />
    <PackageReference Include="Google.GenAI" Version="1.15.0" />
    <PackageReference Include="itext7" Version="9.0.0" />
    <PackageReference Include="itext7.bouncy-castle-adapter" Version="9.0.0" />
    <PackageReference Include="itext7.bouncy-castle-fips-adapter" Version="9.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="6.0.36" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="6.0.36" />
    <PackageReference Include="Tono.Excel" Version="1.0.7" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\GCTL.Core\GCTL.Core.csproj" />
  </ItemGroup>

</Project>
